// Code generated by goyacc - DO NOT EDIT.

/*
BCDiceコマンドの構文解析処理のパッケージ。

BCDiceのコマンドはLALR(1)文法で表現できる。
BCDiceコマンドのLALR(1)構文解析器は、goyaccを使用して生成する。
*/
package parser

import __yyfmt__ "fmt"

import (
	"fmt"
	"github.com/raa0121/GoBCDice/pkg/core/ast"
	"github.com/raa0121/GoBCDice/pkg/core/lexer"
	"github.com/raa0121/GoBCDice/pkg/core/token"
	"strconv"
)

type yySymType struct {
	yys       int
	token     token.Token
	node      ast.Node
	bRoll     *ast.BRoll
	bRollList *ast.BRollList
}

type yyXError struct {
	state, xsym int
}

const (
	yyDefault    = 57376
	yyEofCode    = 57344
	ASTERISK     = 57352
	B            = 57366
	CALC         = 57371
	CHOICE_BEGIN = 57372
	CHOICE_END   = 57373
	COMMA        = 57364
	D            = 57365
	DIAMOND      = 57359
	DOTS         = 57370
	EQ           = 57354
	GT           = 57356
	GTEQ         = 57358
	IDENT        = 57347
	ILLEGAL      = 57346
	INT          = 57348
	LT           = 57355
	LTEQ         = 57357
	L_BRACKET    = 57362
	L_PAREN      = 57360
	MINUS        = 57351
	PLUS         = 57350
	R            = 57367
	R_BRACKET    = 57363
	R_PAREN      = 57361
	SECRET       = 57369
	SLASH        = 57353
	STRING       = 57349
	U            = 57368
	UMINUS       = 57375
	UPLUS        = 57374
	yyErrCode    = 57345

	yyMaxDepth = 200
	yyTabOfs   = -72
)

var (
	yyPrec = map[int]int{
		EQ:       0,
		LT:       0,
		GT:       0,
		LTEQ:     0,
		GTEQ:     0,
		DIAMOND:  0,
		PLUS:     1,
		MINUS:    1,
		ASTERISK: 2,
		SLASH:    2,
		D:        3,
		B:        3,
		DOTS:     4,
		UPLUS:    5,
		UMINUS:   5,
	}

	yyXLAT = map[int]int{
		57350: 0,  // PLUS (124x)
		57351: 1,  // MINUS (120x)
		57352: 2,  // ASTERISK (79x)
		57353: 3,  // SLASH (79x)
		57344: 4,  // $end (70x)
		57361: 5,  // R_PAREN (65x)
		57367: 6,  // R (58x)
		57368: 7,  // U (58x)
		57360: 8,  // L_PAREN (47x)
		57348: 9,  // INT (46x)
		57384: 10, // int (46x)
		57359: 11, // DIAMOND (44x)
		57354: 12, // EQ (44x)
		57356: 13, // GT (44x)
		57358: 14, // GTEQ (44x)
		57355: 15, // LT (44x)
		57357: 16, // LTEQ (44x)
		57362: 17, // L_BRACKET (23x)
		57387: 18, // rand (23x)
		57385: 19, // int_expr (21x)
		57386: 20, // int_rand_expr (20x)
		57389: 21, // roll_operand (15x)
		57381: 22, // d_roll (12x)
		57383: 23, // d_roll_expr (12x)
		57366: 24, // B (10x)
		57365: 25, // D (7x)
		57370: 26, // DOTS (4x)
		57363: 27, // R_BRACKET (4x)
		57377: 28, // b_roll (2x)
		57388: 29, // rand_operand (2x)
		57378: 30, // b_roll_comp (1x)
		57379: 31, // b_roll_list (1x)
		57371: 32, // CALC (1x)
		57380: 33, // command (1x)
		57382: 34, // d_roll_comp (1x)
		57376: 35, // $default (0x)
		57372: 36, // CHOICE_BEGIN (0x)
		57373: 37, // CHOICE_END (0x)
		57364: 38, // COMMA (0x)
		57345: 39, // error (0x)
		57347: 40, // IDENT (0x)
		57346: 41, // ILLEGAL (0x)
		57369: 42, // SECRET (0x)
		57349: 43, // STRING (0x)
		57375: 44, // UMINUS (0x)
		57374: 45, // UPLUS (0x)
	}

	yySymNames = []string{
		"PLUS",
		"MINUS",
		"ASTERISK",
		"SLASH",
		"$end",
		"R_PAREN",
		"R",
		"U",
		"L_PAREN",
		"INT",
		"int",
		"DIAMOND",
		"EQ",
		"GT",
		"GTEQ",
		"LT",
		"LTEQ",
		"L_BRACKET",
		"rand",
		"int_expr",
		"int_rand_expr",
		"roll_operand",
		"d_roll",
		"d_roll_expr",
		"B",
		"D",
		"DOTS",
		"R_BRACKET",
		"b_roll",
		"rand_operand",
		"b_roll_comp",
		"b_roll_list",
		"CALC",
		"command",
		"d_roll_comp",
		"$default",
		"CHOICE_BEGIN",
		"CHOICE_END",
		"COMMA",
		"error",
		"IDENT",
		"ILLEGAL",
		"SECRET",
		"STRING",
		"UMINUS",
		"UPLUS",
	}

	yyTokenLiteralStrings = map[int]string{}

	yyReductions = map[int]struct{ xsym, components int }{
		0:  {0, 1},
		1:  {33, 1},
		2:  {33, 1},
		3:  {33, 1},
		4:  {33, 1},
		5:  {33, 4},
		6:  {19, 1},
		7:  {19, 3},
		8:  {19, 2},
		9:  {19, 2},
		10: {19, 3},
		11: {19, 3},
		12: {19, 3},
		13: {19, 3},
		14: {19, 4},
		15: {19, 4},
		16: {20, 1},
		17: {20, 1},
		18: {20, 3},
		19: {20, 2},
		20: {20, 2},
		21: {20, 3},
		22: {20, 3},
		23: {20, 3},
		24: {20, 3},
		25: {20, 4},
		26: {20, 4},
		27: {23, 1},
		28: {23, 3},
		29: {23, 2},
		30: {23, 2},
		31: {23, 3},
		32: {23, 3},
		33: {23, 3},
		34: {23, 3},
		35: {23, 4},
		36: {23, 4},
		37: {23, 3},
		38: {23, 3},
		39: {23, 3},
		40: {23, 3},
		41: {23, 4},
		42: {23, 4},
		43: {23, 3},
		44: {23, 3},
		45: {23, 3},
		46: {23, 3},
		47: {23, 4},
		48: {23, 4},
		49: {34, 3},
		50: {34, 3},
		51: {34, 3},
		52: {34, 3},
		53: {34, 3},
		54: {34, 3},
		55: {31, 1},
		56: {31, 3},
		57: {30, 3},
		58: {30, 3},
		59: {30, 3},
		60: {30, 3},
		61: {30, 3},
		62: {30, 3},
		63: {21, 1},
		64: {21, 1},
		65: {21, 3},
		66: {22, 3},
		67: {28, 3},
		68: {29, 1},
		69: {29, 3},
		70: {18, 5},
		71: {10, 1},
	}

	yyXErrors = map[yyXError]string{}

	yyParseTab = [141][]uint16{
		// 0
		{83, 82, 8: 81, 89, 79, 17: 88, 80, 20: 84, 87, 85, 74, 28: 86, 30: 77, 76, 78, 73, 75},
		{4: 72},
		{151, 152, 153, 154, 71, 11: 202, 201, 204, 206, 203, 205},
		{4: 70},
		{186, 4: 69, 11: 188, 187, 190, 192, 189, 191},
		// 5
		{4: 68},
		{8: 183},
		{56, 56, 56, 56, 56, 56, 56, 56, 11: 56, 56, 56, 56, 56, 56, 24: 9, 9},
		{55, 55, 55, 55, 55, 55, 55, 55, 11: 55, 55, 55, 55, 55, 55, 24: 8, 8},
		{83, 82, 8: 81, 89, 79, 17: 88, 80, 20: 179, 150, 85, 180},
		// 10
		{83, 82, 8: 81, 89, 79, 17: 88, 80, 20: 177, 150, 85, 178},
		{83, 82, 8: 81, 89, 79, 17: 88, 80, 20: 175, 150, 85, 176},
		{144, 145, 146, 147},
		{45, 45, 45, 45, 45, 45, 45, 45, 11: 45, 45, 45, 45, 45, 45},
		{17, 4: 17, 11: 17, 17, 17, 17, 17, 17},
		// 15
		{24: 117, 116},
		{8: 91, 89, 90, 29: 92},
		{1, 1, 1, 1, 1, 1, 1, 1, 11: 1, 1, 1, 1, 1, 1, 24: 1, 1, 1, 1},
		{26: 4, 4},
		{99, 98, 8: 97, 89, 96, 19: 100},
		// 20
		{26: 93},
		{8: 91, 89, 90, 29: 94},
		{27: 95},
		{2, 2, 2, 2, 2, 2, 2, 2, 11: 2, 2, 2, 2, 2, 2, 24: 2, 2},
		{66, 66, 66, 66, 66, 66, 66, 66},
		// 25
		{99, 98, 8: 97, 89, 96, 19: 114},
		{99, 98, 8: 97, 89, 96, 19: 113},
		{99, 98, 8: 97, 89, 96, 19: 112},
		{101, 102, 103, 104, 5: 105},
		{99, 98, 8: 97, 89, 96, 19: 111},
		// 30
		{99, 98, 8: 97, 89, 96, 19: 110},
		{99, 98, 8: 97, 89, 96, 19: 109},
		{99, 98, 8: 97, 89, 96, 19: 106},
		{26: 3, 3},
		{59, 59, 59, 59, 59, 59, 108, 107},
		// 35
		{58, 58, 58, 58, 58, 58, 58, 58},
		{57, 57, 57, 57, 57, 57, 57, 57},
		{60, 60, 60, 60, 60, 60, 60, 60},
		{61, 61, 103, 104, 61, 61, 61, 61},
		{62, 62, 103, 104, 62, 62, 62, 62},
		// 40
		{63, 63, 63, 63, 63, 63, 63, 63},
		{64, 64, 64, 64, 64, 64, 64, 64},
		{101, 102, 103, 104, 5: 115},
		{65, 65, 65, 65, 65, 65, 65, 65},
		{8: 120, 89, 118, 17: 88, 119, 21: 143},
		// 45
		{8: 120, 89, 118, 17: 88, 119, 21: 121},
		{9, 9, 9, 9, 9, 9, 9, 9, 11: 9, 9, 9, 9, 9, 9, 24: 9},
		{8, 8, 8, 8, 8, 8, 8, 8, 11: 8, 8, 8, 8, 8, 8, 24: 8},
		{126, 125, 8: 124, 89, 122, 17: 88, 123, 20: 127},
		{5, 4: 5, 11: 5, 5, 5, 5, 5, 5},
		// 50
		{56, 56, 56, 56, 5: 56, 56, 56},
		{55, 55, 55, 55, 5: 55, 55, 55},
		{126, 125, 8: 124, 89, 122, 17: 88, 123, 20: 141},
		{126, 125, 8: 124, 89, 122, 17: 88, 123, 20: 140},
		{126, 125, 8: 124, 89, 122, 17: 88, 123, 20: 139},
		// 55
		{128, 129, 130, 131, 5: 132},
		{126, 125, 8: 124, 89, 122, 17: 88, 123, 20: 138},
		{126, 125, 8: 124, 89, 122, 17: 88, 123, 20: 137},
		{126, 125, 8: 124, 89, 122, 17: 88, 123, 20: 136},
		{126, 125, 8: 124, 89, 122, 17: 88, 123, 20: 133},
		// 60
		{7, 7, 7, 7, 7, 7, 7, 7, 11: 7, 7, 7, 7, 7, 7, 24: 7},
		{48, 48, 48, 48, 5: 48, 135, 134},
		{47, 47, 47, 47, 47, 47, 47, 47, 11: 47, 47, 47, 47, 47, 47},
		{46, 46, 46, 46, 46, 46, 46, 46, 11: 46, 46, 46, 46, 46, 46},
		{49, 49, 49, 49, 5: 49, 49, 49},
		// 65
		{50, 50, 130, 131, 5: 50, 50, 50},
		{51, 51, 130, 131, 5: 51, 51, 51},
		{52, 52, 52, 52, 5: 52, 52, 52},
		{53, 53, 53, 53, 5: 53, 53, 53},
		{128, 129, 130, 131, 5: 142},
		// 70
		{54, 54, 54, 54, 5: 54, 54, 54},
		{6, 6, 6, 6, 6, 6, 6, 6, 11: 6, 6, 6, 6, 6, 6},
		{83, 82, 8: 81, 89, 79, 17: 88, 80, 20: 173, 150, 85, 174},
		{83, 82, 8: 81, 89, 79, 17: 88, 80, 20: 171, 150, 85, 172},
		{83, 82, 8: 81, 89, 79, 17: 88, 80, 20: 169, 150, 85, 170},
		// 75
		{83, 82, 8: 81, 89, 79, 17: 88, 80, 20: 148, 150, 85, 149},
		{48, 48, 48, 48, 48, 48, 135, 134, 11: 48, 48, 48, 48, 48, 48},
		{32, 32, 32, 32, 32, 32, 156, 155, 11: 32, 32, 32, 32, 32, 32},
		{25: 116},
		{83, 82, 8: 81, 89, 79, 17: 88, 80, 20: 167, 150, 85, 168},
		// 80
		{83, 82, 8: 81, 89, 79, 17: 88, 80, 20: 165, 150, 85, 166},
		{83, 82, 8: 81, 89, 79, 17: 88, 80, 20: 163, 150, 85, 164},
		{83, 82, 8: 81, 89, 79, 17: 88, 80, 20: 157, 150, 85, 158},
		{31, 31, 31, 31, 31, 31, 31, 31, 11: 31, 31, 31, 31, 31, 31},
		{30, 30, 30, 30, 30, 30, 30, 30, 11: 30, 30, 30, 30, 30, 30},
		// 85
		{26, 26, 26, 26, 26, 26, 162, 161, 11: 26, 26, 26, 26, 26, 26},
		{38, 38, 38, 38, 38, 38, 160, 159, 11: 38, 38, 38, 38, 38, 38},
		{37, 37, 37, 37, 37, 37, 37, 37, 11: 37, 37, 37, 37, 37, 37},
		{36, 36, 36, 36, 36, 36, 36, 36, 11: 36, 36, 36, 36, 36, 36},
		{25, 25, 25, 25, 25, 25, 25, 25, 11: 25, 25, 25, 25, 25, 25},
		// 90
		{24, 24, 24, 24, 24, 24, 24, 24, 11: 24, 24, 24, 24, 24, 24},
		{27, 27, 27, 27, 27, 27, 27, 27, 11: 27, 27, 27, 27, 27, 27},
		{39, 39, 39, 39, 39, 39, 39, 39, 11: 39, 39, 39, 39, 39, 39},
		{28, 28, 146, 147, 28, 28, 28, 28, 11: 28, 28, 28, 28, 28, 28},
		{40, 40, 153, 154, 40, 40, 40, 40, 11: 40, 40, 40, 40, 40, 40},
		// 95
		{29, 29, 146, 147, 29, 29, 29, 29, 11: 29, 29, 29, 29, 29, 29},
		{41, 41, 153, 154, 41, 41, 41, 41, 11: 41, 41, 41, 41, 41, 41},
		{49, 49, 49, 49, 49, 49, 49, 49, 11: 49, 49, 49, 49, 49, 49},
		{33, 33, 33, 33, 33, 33, 33, 33, 11: 33, 33, 33, 33, 33, 33},
		{50, 50, 146, 147, 50, 50, 50, 50, 11: 50, 50, 50, 50, 50, 50},
		// 100
		{34, 34, 153, 154, 34, 34, 34, 34, 11: 34, 34, 34, 34, 34, 34},
		{51, 51, 146, 147, 51, 51, 51, 51, 11: 51, 51, 51, 51, 51, 51},
		{35, 35, 153, 154, 35, 35, 35, 35, 11: 35, 35, 35, 35, 35, 35},
		{52, 52, 52, 52, 52, 52, 52, 52, 11: 52, 52, 52, 52, 52, 52},
		{42, 42, 42, 42, 42, 42, 42, 42, 11: 42, 42, 42, 42, 42, 42},
		// 105
		{53, 53, 53, 53, 53, 53, 53, 53, 11: 53, 53, 53, 53, 53, 53},
		{43, 43, 43, 43, 43, 43, 43, 43, 11: 43, 43, 43, 43, 43, 43},
		{144, 145, 146, 147, 5: 182},
		{151, 152, 153, 154, 5: 181},
		{44, 44, 44, 44, 44, 44, 44, 44, 11: 44, 44, 44, 44, 44, 44},
		// 110
		{54, 54, 54, 54, 54, 54, 54, 54, 11: 54, 54, 54, 54, 54, 54, 24: 7, 7},
		{99, 98, 8: 97, 89, 96, 19: 184},
		{101, 102, 103, 104, 5: 185},
		{4: 67},
		{8: 120, 89, 118, 17: 88, 119, 21: 200, 28: 199},
		// 115
		{99, 98, 8: 97, 89, 96, 19: 198},
		{99, 98, 8: 97, 89, 96, 19: 197},
		{99, 98, 8: 97, 89, 96, 19: 196},
		{99, 98, 8: 97, 89, 96, 19: 195},
		{99, 98, 8: 97, 89, 96, 19: 194},
		// 120
		{99, 98, 8: 97, 89, 96, 19: 193},
		{101, 102, 103, 104, 10},
		{101, 102, 103, 104, 11},
		{101, 102, 103, 104, 12},
		{101, 102, 103, 104, 13},
		// 125
		{101, 102, 103, 104, 14},
		{101, 102, 103, 104, 15},
		{16, 4: 16, 11: 16, 16, 16, 16, 16, 16},
		{24: 117},
		{99, 98, 8: 97, 89, 96, 19: 212},
		// 130
		{99, 98, 8: 97, 89, 96, 19: 211},
		{99, 98, 8: 97, 89, 96, 19: 210},
		{99, 98, 8: 97, 89, 96, 19: 209},
		{99, 98, 8: 97, 89, 96, 19: 208},
		{99, 98, 8: 97, 89, 96, 19: 207},
		// 135
		{101, 102, 103, 104, 18},
		{101, 102, 103, 104, 19},
		{101, 102, 103, 104, 20},
		{101, 102, 103, 104, 21},
		{101, 102, 103, 104, 22},
		// 140
		{101, 102, 103, 104, 23},
	}
)

var yyDebug = 0

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyLexerEx interface {
	yyLexer
	Reduced(rule, state int, lval *yySymType) bool
}

func yySymName(c int) (s string) {
	x, ok := yyXLAT[c]
	if ok {
		return yySymNames[x]
	}

	if c < 0x7f {
		return __yyfmt__.Sprintf("%q", c)
	}

	return __yyfmt__.Sprintf("%d", c)
}

func yylex1(yylex yyLexer, lval *yySymType) (n int) {
	n = yylex.Lex(lval)
	if n <= 0 {
		n = yyEofCode
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("\nlex %s(%#x %d), lval: %+v\n", yySymName(n), n, n, lval)
	}
	return n
}

func yyParse(yylex yyLexer) int {
	const yyError = 39

	yyEx, _ := yylex.(yyLexerEx)
	var yyn int
	var yylval yySymType
	var yyVAL yySymType
	yyS := make([]yySymType, 200)

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yyerrok := func() {
		if yyDebug >= 2 {
			__yyfmt__.Printf("yyerrok()\n")
		}
		Errflag = 0
	}
	_ = yyerrok
	yystate := 0
	yychar := -1
	var yyxchar int
	var yyshift int
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	if yychar < 0 {
		yylval.yys = yystate
		yychar = yylex1(yylex, &yylval)
		var ok bool
		if yyxchar, ok = yyXLAT[yychar]; !ok {
			yyxchar = len(yySymNames) // > tab width
		}
	}
	if yyDebug >= 4 {
		var a []int
		for _, v := range yyS[:yyp+1] {
			a = append(a, v.yys)
		}
		__yyfmt__.Printf("state stack %v\n", a)
	}
	row := yyParseTab[yystate]
	yyn = 0
	if yyxchar < len(row) {
		if yyn = int(row[yyxchar]); yyn != 0 {
			yyn += yyTabOfs
		}
	}
	switch {
	case yyn > 0: // shift
		yychar = -1
		yyVAL = yylval
		yystate = yyn
		yyshift = yyn
		if yyDebug >= 2 {
			__yyfmt__.Printf("shift, and goto state %d\n", yystate)
		}
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	case yyn < 0: // reduce
	case yystate == 1: // accept
		if yyDebug >= 2 {
			__yyfmt__.Println("accept")
		}
		goto ret0
	}

	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			if yyDebug >= 1 {
				__yyfmt__.Printf("no action for %s in state %d\n", yySymName(yychar), yystate)
			}
			msg, ok := yyXErrors[yyXError{yystate, yyxchar}]
			if !ok {
				msg, ok = yyXErrors[yyXError{yystate, -1}]
			}
			if !ok && yyshift != 0 {
				msg, ok = yyXErrors[yyXError{yyshift, yyxchar}]
			}
			if !ok {
				msg, ok = yyXErrors[yyXError{yyshift, -1}]
			}
			if yychar > 0 {
				ls := yyTokenLiteralStrings[yychar]
				if ls == "" {
					ls = yySymName(yychar)
				}
				if ls != "" {
					switch {
					case msg == "":
						msg = __yyfmt__.Sprintf("unexpected %s", ls)
					default:
						msg = __yyfmt__.Sprintf("unexpected %s, %s", ls, msg)
					}
				}
			}
			if msg == "" {
				msg = "syntax error"
			}
			yylex.Error(msg)
			Nerrs++
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				row := yyParseTab[yyS[yyp].yys]
				if yyError < len(row) {
					yyn = int(row[yyError]) + yyTabOfs
					if yyn > 0 { // hit
						if yyDebug >= 2 {
							__yyfmt__.Printf("error recovery found error shift in state %d\n", yyS[yyp].yys)
						}
						yystate = yyn /* simulate a shift of "error" */
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery failed\n")
			}
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yySymName(yychar))
			}
			if yychar == yyEofCode {
				goto ret1
			}

			yychar = -1
			goto yynewstate /* try again in the same state */
		}
	}

	r := -yyn
	x0 := yyReductions[r]
	x, n := x0.xsym, x0.components
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= n
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	exState := yystate
	yystate = int(yyParseTab[yyS[yyp].yys][x]) + yyTabOfs
	/* reduction by production r */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce using rule %v (%s), and goto state %d\n", r, yySymNames[x], yystate)
	}

	switch r {
	case 1:
		{
			yyVAL.node = ast.NewDRollExpr(yyS[yypt-0].node.Token(), yyS[yypt-0].node)
			yylex.(*LexerWrapper).ast = yyVAL.node
		}
	case 2:
		{
			yyVAL.node = ast.NewDRollComp(yyS[yypt-0].node.Token(), yyS[yypt-0].node)
			yylex.(*LexerWrapper).ast = yyVAL.node
		}
	case 3:
		{
			yyVAL.node = yyS[yypt-0].bRollList
			yylex.(*LexerWrapper).ast = yyVAL.node
		}
	case 4:
		{
			yyVAL.node = ast.NewBRollComp(yyS[yypt-0].node.Token(), yyS[yypt-0].node)
			yylex.(*LexerWrapper).ast = yyVAL.node
		}
	case 5:
		{
			yyVAL.node = ast.NewCalc(yyS[yypt-3].token, yyS[yypt-1].node)
			yylex.(*LexerWrapper).ast = yyVAL.node
		}
	case 7:
		{
			yyVAL.node = yyS[yypt-1].node
		}
	case 8:
		{
			yyVAL.node = ast.NewUnaryMinus(yyS[yypt-1].token, yyS[yypt-0].node)
		}
	case 9:
		{
			yyVAL.node = yyS[yypt-0].node
		}
	case 10:
		{
			yyVAL.node = ast.NewAdd(yyS[yypt-2].node, yyS[yypt-1].token, yyS[yypt-0].node)
		}
	case 11:
		{
			yyVAL.node = ast.NewSubtract(yyS[yypt-2].node, yyS[yypt-1].token, yyS[yypt-0].node)
		}
	case 12:
		{
			yyVAL.node = ast.NewMultiply(yyS[yypt-2].node, yyS[yypt-1].token, yyS[yypt-0].node)
		}
	case 13:
		{
			yyVAL.node = ast.NewDivideWithRoundingDown(yyS[yypt-2].node, yyS[yypt-1].token, yyS[yypt-0].node)
		}
	case 14:
		{
			yyVAL.node = ast.NewDivideWithRoundingUp(yyS[yypt-3].node, yyS[yypt-2].token, yyS[yypt-1].node)
		}
	case 15:
		{
			yyVAL.node = ast.NewDivideWithRounding(yyS[yypt-3].node, yyS[yypt-2].token, yyS[yypt-1].node)
		}
	case 18:
		{
			yyVAL.node = yyS[yypt-1].node
		}
	case 19:
		{
			yyVAL.node = ast.NewUnaryMinus(yyS[yypt-1].token, yyS[yypt-0].node)
		}
	case 20:
		{
			yyVAL.node = yyS[yypt-0].node
		}
	case 21:
		{
			yyVAL.node = ast.NewAdd(yyS[yypt-2].node, yyS[yypt-1].token, yyS[yypt-0].node)
		}
	case 22:
		{
			yyVAL.node = ast.NewSubtract(yyS[yypt-2].node, yyS[yypt-1].token, yyS[yypt-0].node)
		}
	case 23:
		{
			yyVAL.node = ast.NewMultiply(yyS[yypt-2].node, yyS[yypt-1].token, yyS[yypt-0].node)
		}
	case 24:
		{
			yyVAL.node = ast.NewDivideWithRoundingDown(yyS[yypt-2].node, yyS[yypt-1].token, yyS[yypt-0].node)
		}
	case 25:
		{
			yyVAL.node = ast.NewDivideWithRoundingUp(yyS[yypt-3].node, yyS[yypt-2].token, yyS[yypt-1].node)
		}
	case 26:
		{
			yyVAL.node = ast.NewDivideWithRounding(yyS[yypt-3].node, yyS[yypt-2].token, yyS[yypt-1].node)
		}
	case 28:
		{
			yyVAL.node = yyS[yypt-1].node
		}
	case 29:
		{
			yyVAL.node = ast.NewUnaryMinus(yyS[yypt-1].token, yyS[yypt-0].node)
		}
	case 30:
		{
			yyVAL.node = yyS[yypt-0].node
		}
	case 31:
		{
			yyVAL.node = ast.NewAdd(yyS[yypt-2].node, yyS[yypt-1].token, yyS[yypt-0].node)
		}
	case 32:
		{
			yyVAL.node = ast.NewSubtract(yyS[yypt-2].node, yyS[yypt-1].token, yyS[yypt-0].node)
		}
	case 33:
		{
			yyVAL.node = ast.NewMultiply(yyS[yypt-2].node, yyS[yypt-1].token, yyS[yypt-0].node)
		}
	case 34:
		{
			yyVAL.node = ast.NewDivideWithRoundingDown(yyS[yypt-2].node, yyS[yypt-1].token, yyS[yypt-0].node)
		}
	case 35:
		{
			yyVAL.node = ast.NewDivideWithRoundingUp(yyS[yypt-3].node, yyS[yypt-2].token, yyS[yypt-1].node)
		}
	case 36:
		{
			yyVAL.node = ast.NewDivideWithRounding(yyS[yypt-3].node, yyS[yypt-2].token, yyS[yypt-1].node)
		}
	case 37:
		{
			yyVAL.node = ast.NewAdd(yyS[yypt-2].node, yyS[yypt-1].token, yyS[yypt-0].node)
		}
	case 38:
		{
			yyVAL.node = ast.NewSubtract(yyS[yypt-2].node, yyS[yypt-1].token, yyS[yypt-0].node)
		}
	case 39:
		{
			yyVAL.node = ast.NewMultiply(yyS[yypt-2].node, yyS[yypt-1].token, yyS[yypt-0].node)
		}
	case 40:
		{
			yyVAL.node = ast.NewDivideWithRoundingDown(yyS[yypt-2].node, yyS[yypt-1].token, yyS[yypt-0].node)
		}
	case 41:
		{
			yyVAL.node = ast.NewDivideWithRoundingUp(yyS[yypt-3].node, yyS[yypt-2].token, yyS[yypt-1].node)
		}
	case 42:
		{
			yyVAL.node = ast.NewDivideWithRounding(yyS[yypt-3].node, yyS[yypt-2].token, yyS[yypt-1].node)
		}
	case 43:
		{
			yyVAL.node = ast.NewAdd(yyS[yypt-2].node, yyS[yypt-1].token, yyS[yypt-0].node)
		}
	case 44:
		{
			yyVAL.node = ast.NewSubtract(yyS[yypt-2].node, yyS[yypt-1].token, yyS[yypt-0].node)
		}
	case 45:
		{
			yyVAL.node = ast.NewMultiply(yyS[yypt-2].node, yyS[yypt-1].token, yyS[yypt-0].node)
		}
	case 46:
		{
			yyVAL.node = ast.NewDivideWithRoundingDown(yyS[yypt-2].node, yyS[yypt-1].token, yyS[yypt-0].node)
		}
	case 47:
		{
			yyVAL.node = ast.NewDivideWithRoundingUp(yyS[yypt-3].node, yyS[yypt-2].token, yyS[yypt-1].node)
		}
	case 48:
		{
			yyVAL.node = ast.NewDivideWithRounding(yyS[yypt-3].node, yyS[yypt-2].token, yyS[yypt-1].node)
		}
	case 49:
		{
			yyVAL.node = ast.NewCompare(yyS[yypt-2].node, yyS[yypt-1].token, yyS[yypt-0].node)
		}
	case 50:
		{
			yyVAL.node = ast.NewCompare(yyS[yypt-2].node, yyS[yypt-1].token, yyS[yypt-0].node)
		}
	case 51:
		{
			yyVAL.node = ast.NewCompare(yyS[yypt-2].node, yyS[yypt-1].token, yyS[yypt-0].node)
		}
	case 52:
		{
			yyVAL.node = ast.NewCompare(yyS[yypt-2].node, yyS[yypt-1].token, yyS[yypt-0].node)
		}
	case 53:
		{
			yyVAL.node = ast.NewCompare(yyS[yypt-2].node, yyS[yypt-1].token, yyS[yypt-0].node)
		}
	case 54:
		{
			yyVAL.node = ast.NewCompare(yyS[yypt-2].node, yyS[yypt-1].token, yyS[yypt-0].node)
		}
	case 55:
		{
			yyVAL.bRollList = ast.NewBRollList(yyS[yypt-0].bRoll)
		}
	case 56:
		{
			yyVAL.bRollList.Append(yyS[yypt-0].bRoll)
		}
	case 57:
		{
			yyVAL.node = ast.NewCompare(yyS[yypt-2].bRollList, yyS[yypt-1].token, yyS[yypt-0].node)
		}
	case 58:
		{
			yyVAL.node = ast.NewCompare(yyS[yypt-2].bRollList, yyS[yypt-1].token, yyS[yypt-0].node)
		}
	case 59:
		{
			yyVAL.node = ast.NewCompare(yyS[yypt-2].bRollList, yyS[yypt-1].token, yyS[yypt-0].node)
		}
	case 60:
		{
			yyVAL.node = ast.NewCompare(yyS[yypt-2].bRollList, yyS[yypt-1].token, yyS[yypt-0].node)
		}
	case 61:
		{
			yyVAL.node = ast.NewCompare(yyS[yypt-2].bRollList, yyS[yypt-1].token, yyS[yypt-0].node)
		}
	case 62:
		{
			yyVAL.node = ast.NewCompare(yyS[yypt-2].bRollList, yyS[yypt-1].token, yyS[yypt-0].node)
		}
	case 65:
		{
			yyVAL.node = yyS[yypt-1].node
		}
	case 66:
		{
			yyVAL.node = ast.NewDRoll(yyS[yypt-2].node, yyS[yypt-1].token, yyS[yypt-0].node)
		}
	case 67:
		{
			yyVAL.bRoll = ast.NewBRoll(yyS[yypt-2].node, yyS[yypt-1].token, yyS[yypt-0].node)
		}
	case 69:
		{
			yyVAL.node = yyS[yypt-1].node
		}
	case 70:
		{
			yyVAL.node = ast.NewRandomNumber(yyS[yypt-3].node, yyS[yypt-2].token, yyS[yypt-1].node)
		}
	case 71:
		{
			// TODO: 整数が大きすぎるときなどのエラー処理が必要
			value, _ := strconv.Atoi(yyS[yypt-0].token.Literal)

			yyVAL.node = ast.NewInt(value, yyS[yypt-0].token)
		}

	}

	if yyEx != nil && yyEx.Reduced(r, exState, &yyVAL) {
		return -1
	}
	goto yystack /* stack new state and value */
}

// 字句解析器をyyParseで使用できるようにするためのラッパー。
type LexerWrapper struct {
	// 入力文字列
	Input string
	// 現在の桁
	Column int
	// 現在のルートノード
	ast ast.Node
	// 字句解析器
	lexer *lexer.Lexer
	// エラーの内容
	err string
}

// トークンの種類とyyParseで使用する定数との対応
var tokenTypeToYYTokenType = map[token.TokenType]int{
	token.ILLEGAL: ILLEGAL,

	token.IDENT:  IDENT,
	token.INT:    INT,
	token.STRING: STRING,

	token.PLUS:     PLUS,
	token.MINUS:    MINUS,
	token.ASTERISK: ASTERISK,
	token.SLASH:    SLASH,

	token.EQ:      EQ,
	token.LT:      LT,
	token.GT:      GT,
	token.LTEQ:    LTEQ,
	token.GTEQ:    GTEQ,
	token.DIAMOND: DIAMOND,

	token.L_PAREN:   L_PAREN,
	token.R_PAREN:   R_PAREN,
	token.L_BRACKET: L_BRACKET,
	token.R_BRACKET: R_BRACKET,
	token.COMMA:     COMMA,

	token.D:      D,
	token.B:      B,
	token.R:      R,
	token.U:      U,
	token.SECRET: SECRET,
	token.DOTS:   DOTS,

	token.CALC: CALC,

	token.CHOICE_BEGIN: CHOICE_BEGIN,
	token.CHOICE_END:   CHOICE_END,
}

// newLexerWrapper は新しい字句解析器ラッパーを作る。
//
// input: 入力文字列
func newLexerWrapper(input string) *LexerWrapper {
	lw := &LexerWrapper{
		Input: input,
		lexer: lexer.New(input),
	}

	return lw
}

// Lex は次のトークンを読み込み、対応する定数を返す。
//
// 文字列の終端に達した場合は0を返す。
func (lw *LexerWrapper) Lex(lval *yySymType) int {
	tok := lw.lexer.NextToken()
	lw.Column = tok.Column

	if tok.Type == token.EOT {
		return 0
	}

	lval.token = tok

	yyTokenType, ok := tokenTypeToYYTokenType[tok.Type]
	if !ok {
		return ILLEGAL
	}

	return yyTokenType
}

// Error は発生したエラーを記録する。
func (lw *LexerWrapper) Error(e string) {
	lw.err = fmt.Sprintf("column %d: %s", lw.Column, e)
}

// Parse は入力文字列をBCDiceコマンドとして構文解析する。
// 構文解析に成功した場合は、抽象構文木のルートノードを返す。
// 構文解析に失敗した場合は、エラーを返す。
func Parse(input string) (ast.Node, error) {
	lw := newLexerWrapper(input)

	if yyParse(lw) != 0 {
		return nil, fmt.Errorf(lw.err)
	} else {
		return lw.ast, nil
	}
}

/* vim: set filetype=goyacc: */
