// Code generated by pigeon; DO NOT EDIT.

package parser

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"io/ioutil"
	"math"
	"os"
	"sort"
	"strconv"
	"strings"
	"sync"
	"unicode"
	"unicode/utf8"

	"github.com/raa0121/GoBCDice/pkg/core/ast"
)

func toIfaceSlice(v interface{}) []interface{} {
	if v == nil {
		return nil
	}
	return v.([]interface{})
}

func leftAssociativeAdditive(first interface{}, rest interface{}) (ast.Node, error) {
	lastNode := first.(ast.Node)
	for _, r := range toIfaceSlice(rest) {
		rs := toIfaceSlice(r)
		op := string(rs[0].([]byte))
		right := rs[1].(ast.Node)

		switch op {
		case "+":
			lastNode = ast.NewAdd(lastNode, right)
		case "-":
			lastNode = ast.NewSubtract(lastNode, right)
		}
	}

	return lastNode, nil
}

func leftAssociativeMultitive(first interface{}, rest interface{}) (ast.Node, error) {
	lastNode := first.(ast.Node)
	for _, r := range toIfaceSlice(rest) {
		rs := toIfaceSlice(r)
		op := string(rs[0].([]byte))
		right := rs[1].(ast.Node)

		roundingMethod := ""
		if len(rs) >= 3 {
			roundingMethod = strings.ToUpper(string(rs[2].([]byte)))
		}

		switch op {
		case "*":
			lastNode = ast.NewMultiply(lastNode, right)
		case "/":
			switch roundingMethod {
			case "U":
				lastNode = ast.NewDivideWithRoundingUp(lastNode, right)
			case "R":
				lastNode = ast.NewDivideWithRounding(lastNode, right)
			case "":
				lastNode = ast.NewDivideWithRoundingDown(lastNode, right)
			}
		}
	}

	return lastNode, nil
}

var g = &grammar{
	rules: []*rule{
		{
			name: "Command",
			pos:  position{line: 69, col: 1, offset: 1372},
			expr: &actionExpr{
				pos: position{line: 69, col: 12, offset: 1383},
				run: (*parser).callonCommand1,
				expr: &seqExpr{
					pos: position{line: 69, col: 12, offset: 1383},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 69, col: 12, offset: 1383},
							name: "ResetRandCount",
						},
						&labeledExpr{
							pos:   position{line: 69, col: 27, offset: 1398},
							label: "n",
							expr: &choiceExpr{
								pos: position{line: 69, col: 30, offset: 1401},
								alternatives: []interface{}{
									&ruleRefExpr{
										pos:  position{line: 69, col: 30, offset: 1401},
										name: "Choice",
									},
									&ruleRefExpr{
										pos:  position{line: 69, col: 39, offset: 1410},
										name: "Calc",
									},
									&ruleRefExpr{
										pos:  position{line: 69, col: 46, offset: 1417},
										name: "CommandWithExpression",
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "CommandWithExpression",
			pos:  position{line: 73, col: 1, offset: 1460},
			expr: &actionExpr{
				pos: position{line: 73, col: 26, offset: 1485},
				run: (*parser).callonCommandWithExpression1,
				expr: &seqExpr{
					pos: position{line: 73, col: 26, offset: 1485},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 73, col: 26, offset: 1485},
							label: "n",
							expr: &choiceExpr{
								pos: position{line: 73, col: 29, offset: 1488},
								alternatives: []interface{}{
									&ruleRefExpr{
										pos:  position{line: 73, col: 29, offset: 1488},
										name: "BRollComp",
									},
									&ruleRefExpr{
										pos:  position{line: 73, col: 41, offset: 1500},
										name: "BRollList",
									},
									&ruleRefExpr{
										pos:  position{line: 73, col: 53, offset: 1512},
										name: "RRollComp",
									},
									&ruleRefExpr{
										pos:  position{line: 73, col: 65, offset: 1524},
										name: "RRollList",
									},
									&ruleRefExpr{
										pos:  position{line: 73, col: 77, offset: 1536},
										name: "DRollCompCommand",
									},
									&ruleRefExpr{
										pos:  position{line: 73, col: 96, offset: 1555},
										name: "DRollExprCommand",
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 73, col: 114, offset: 1573},
							name: "EOT",
						},
					},
				},
			},
		},
		{
			name: "Choice",
			pos:  position{line: 77, col: 1, offset: 1597},
			expr: &actionExpr{
				pos: position{line: 77, col: 11, offset: 1607},
				run: (*parser).callonChoice1,
				expr: &seqExpr{
					pos: position{line: 77, col: 11, offset: 1607},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 77, col: 11, offset: 1607},
							val:        "choice[",
							ignoreCase: true,
						},
						&labeledExpr{
							pos:   position{line: 77, col: 22, offset: 1618},
							label: "items",
							expr: &ruleRefExpr{
								pos:  position{line: 77, col: 28, offset: 1624},
								name: "ChoiceItems",
							},
						},
						&zeroOrOneExpr{
							pos: position{line: 77, col: 40, offset: 1636},
							expr: &seqExpr{
								pos: position{line: 77, col: 41, offset: 1637},
								exprs: []interface{}{
									&litMatcher{
										pos:        position{line: 77, col: 41, offset: 1637},
										val:        ",",
										ignoreCase: false,
									},
									&zeroOrMoreExpr{
										pos: position{line: 77, col: 45, offset: 1641},
										expr: &charClassMatcher{
											pos:        position{line: 77, col: 45, offset: 1641},
											val:        "[\\pZ]",
											classes:    []*unicode.RangeTable{rangeTable("Z")},
											ignoreCase: false,
											inverted:   false,
										},
									},
								},
							},
						},
						&litMatcher{
							pos:        position{line: 77, col: 54, offset: 1650},
							val:        "]",
							ignoreCase: false,
						},
					},
				},
			},
		},
		{
			name: "ChoiceItems",
			pos:  position{line: 81, col: 1, offset: 1678},
			expr: &actionExpr{
				pos: position{line: 81, col: 16, offset: 1693},
				run: (*parser).callonChoiceItems1,
				expr: &seqExpr{
					pos: position{line: 81, col: 16, offset: 1693},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 81, col: 16, offset: 1693},
							label: "first",
							expr: &ruleRefExpr{
								pos:  position{line: 81, col: 22, offset: 1699},
								name: "ChoiceItem",
							},
						},
						&labeledExpr{
							pos:   position{line: 81, col: 33, offset: 1710},
							label: "rest",
							expr: &zeroOrMoreExpr{
								pos: position{line: 81, col: 38, offset: 1715},
								expr: &seqExpr{
									pos: position{line: 81, col: 39, offset: 1716},
									exprs: []interface{}{
										&litMatcher{
											pos:        position{line: 81, col: 39, offset: 1716},
											val:        ",",
											ignoreCase: false,
										},
										&ruleRefExpr{
											pos:  position{line: 81, col: 43, offset: 1720},
											name: "ChoiceItem",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "ChoiceItem",
			pos:  position{line: 95, col: 1, offset: 1948},
			expr: &actionExpr{
				pos: position{line: 95, col: 15, offset: 1962},
				run: (*parser).callonChoiceItem1,
				expr: &seqExpr{
					pos: position{line: 95, col: 15, offset: 1962},
					exprs: []interface{}{
						&zeroOrMoreExpr{
							pos: position{line: 95, col: 15, offset: 1962},
							expr: &charClassMatcher{
								pos:        position{line: 95, col: 15, offset: 1962},
								val:        "[\\pZ]",
								classes:    []*unicode.RangeTable{rangeTable("Z")},
								ignoreCase: false,
								inverted:   false,
							},
						},
						&labeledExpr{
							pos:   position{line: 95, col: 22, offset: 1969},
							label: "s",
							expr: &ruleRefExpr{
								pos:  position{line: 95, col: 24, offset: 1971},
								name: "ChoiceItemChars",
							},
						},
					},
				},
			},
		},
		{
			name: "ChoiceItemChars",
			pos:  position{line: 99, col: 1, offset: 2007},
			expr: &actionExpr{
				pos: position{line: 99, col: 20, offset: 2026},
				run: (*parser).callonChoiceItemChars1,
				expr: &oneOrMoreExpr{
					pos: position{line: 99, col: 20, offset: 2026},
					expr: &charClassMatcher{
						pos:        position{line: 99, col: 20, offset: 2026},
						val:        "[^\\],]",
						chars:      []rune{']', ','},
						ignoreCase: false,
						inverted:   true,
					},
				},
			},
		},
		{
			name: "Calc",
			pos:  position{line: 103, col: 1, offset: 2101},
			expr: &actionExpr{
				pos: position{line: 103, col: 9, offset: 2109},
				run: (*parser).callonCalc1,
				expr: &seqExpr{
					pos: position{line: 103, col: 9, offset: 2109},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 103, col: 9, offset: 2109},
							val:        "c",
							ignoreCase: true,
						},
						&litMatcher{
							pos:        position{line: 103, col: 14, offset: 2114},
							val:        "(",
							ignoreCase: false,
						},
						&labeledExpr{
							pos:   position{line: 103, col: 18, offset: 2118},
							label: "expr",
							expr: &ruleRefExpr{
								pos:  position{line: 103, col: 23, offset: 2123},
								name: "IntExpr",
							},
						},
						&litMatcher{
							pos:        position{line: 103, col: 31, offset: 2131},
							val:        ")",
							ignoreCase: false,
						},
					},
				},
			},
		},
		{
			name: "DRollExprCommand",
			pos:  position{line: 107, col: 1, offset: 2182},
			expr: &actionExpr{
				pos: position{line: 107, col: 21, offset: 2202},
				run: (*parser).callonDRollExprCommand1,
				expr: &labeledExpr{
					pos:   position{line: 107, col: 21, offset: 2202},
					label: "expr",
					expr: &ruleRefExpr{
						pos:  position{line: 107, col: 26, offset: 2207},
						name: "DRollExpr",
					},
				},
			},
		},
		{
			name: "DRollCompCommand",
			pos:  position{line: 115, col: 1, offset: 2363},
			expr: &actionExpr{
				pos: position{line: 115, col: 21, offset: 2383},
				run: (*parser).callonDRollCompCommand1,
				expr: &labeledExpr{
					pos:   position{line: 115, col: 21, offset: 2383},
					label: "expr",
					expr: &ruleRefExpr{
						pos:  position{line: 115, col: 26, offset: 2388},
						name: "DRollComp",
					},
				},
			},
		},
		{
			name: "BRollList",
			pos:  position{line: 123, col: 1, offset: 2544},
			expr: &actionExpr{
				pos: position{line: 123, col: 14, offset: 2557},
				run: (*parser).callonBRollList1,
				expr: &seqExpr{
					pos: position{line: 123, col: 14, offset: 2557},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 123, col: 14, offset: 2557},
							label: "first",
							expr: &ruleRefExpr{
								pos:  position{line: 123, col: 20, offset: 2563},
								name: "BRoll",
							},
						},
						&labeledExpr{
							pos:   position{line: 123, col: 26, offset: 2569},
							label: "rest",
							expr: &zeroOrMoreExpr{
								pos: position{line: 123, col: 31, offset: 2574},
								expr: &seqExpr{
									pos: position{line: 123, col: 32, offset: 2575},
									exprs: []interface{}{
										&litMatcher{
											pos:        position{line: 123, col: 32, offset: 2575},
											val:        "+",
											ignoreCase: false,
										},
										&ruleRefExpr{
											pos:  position{line: 123, col: 36, offset: 2579},
											name: "BRoll",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "BRollComp",
			pos:  position{line: 135, col: 1, offset: 2783},
			expr: &actionExpr{
				pos: position{line: 135, col: 14, offset: 2796},
				run: (*parser).callonBRollComp1,
				expr: &seqExpr{
					pos: position{line: 135, col: 14, offset: 2796},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 135, col: 14, offset: 2796},
							label: "left",
							expr: &ruleRefExpr{
								pos:  position{line: 135, col: 19, offset: 2801},
								name: "BRollList",
							},
						},
						&labeledExpr{
							pos:   position{line: 135, col: 29, offset: 2811},
							label: "op",
							expr: &ruleRefExpr{
								pos:  position{line: 135, col: 32, offset: 2814},
								name: "CompareOp",
							},
						},
						&labeledExpr{
							pos:   position{line: 135, col: 42, offset: 2824},
							label: "right",
							expr: &ruleRefExpr{
								pos:  position{line: 135, col: 48, offset: 2830},
								name: "IntExpr",
							},
						},
					},
				},
			},
		},
		{
			name: "RRollList",
			pos:  position{line: 145, col: 1, offset: 2965},
			expr: &actionExpr{
				pos: position{line: 145, col: 14, offset: 2978},
				run: (*parser).callonRRollList1,
				expr: &seqExpr{
					pos: position{line: 145, col: 14, offset: 2978},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 145, col: 14, offset: 2978},
							label: "first",
							expr: &ruleRefExpr{
								pos:  position{line: 145, col: 20, offset: 2984},
								name: "RRoll",
							},
						},
						&labeledExpr{
							pos:   position{line: 145, col: 26, offset: 2990},
							label: "rest",
							expr: &zeroOrMoreExpr{
								pos: position{line: 145, col: 31, offset: 2995},
								expr: &seqExpr{
									pos: position{line: 145, col: 32, offset: 2996},
									exprs: []interface{}{
										&litMatcher{
											pos:        position{line: 145, col: 32, offset: 2996},
											val:        "+",
											ignoreCase: false,
										},
										&ruleRefExpr{
											pos:  position{line: 145, col: 36, offset: 3000},
											name: "RRoll",
										},
									},
								},
							},
						},
						&labeledExpr{
							pos:   position{line: 145, col: 44, offset: 3008},
							label: "th",
							expr: &zeroOrOneExpr{
								pos: position{line: 145, col: 47, offset: 3011},
								expr: &seqExpr{
									pos: position{line: 145, col: 48, offset: 3012},
									exprs: []interface{}{
										&litMatcher{
											pos:        position{line: 145, col: 48, offset: 3012},
											val:        "[",
											ignoreCase: false,
										},
										&ruleRefExpr{
											pos:  position{line: 145, col: 52, offset: 3016},
											name: "IntExpr",
										},
										&litMatcher{
											pos:        position{line: 145, col: 60, offset: 3024},
											val:        "]",
											ignoreCase: false,
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "RRollComp",
			pos:  position{line: 164, col: 1, offset: 3362},
			expr: &actionExpr{
				pos: position{line: 164, col: 14, offset: 3375},
				run: (*parser).callonRRollComp1,
				expr: &seqExpr{
					pos: position{line: 164, col: 14, offset: 3375},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 164, col: 14, offset: 3375},
							label: "left",
							expr: &ruleRefExpr{
								pos:  position{line: 164, col: 19, offset: 3380},
								name: "RRollList",
							},
						},
						&labeledExpr{
							pos:   position{line: 164, col: 29, offset: 3390},
							label: "op",
							expr: &ruleRefExpr{
								pos:  position{line: 164, col: 32, offset: 3393},
								name: "CompareOp",
							},
						},
						&labeledExpr{
							pos:   position{line: 164, col: 42, offset: 3403},
							label: "right",
							expr: &ruleRefExpr{
								pos:  position{line: 164, col: 48, offset: 3409},
								name: "IntExpr",
							},
						},
					},
				},
			},
		},
		{
			name: "IntExpr",
			pos:  position{line: 174, col: 1, offset: 3544},
			expr: &ruleRefExpr{
				pos:  position{line: 174, col: 12, offset: 3555},
				name: "IntExprAdditive",
			},
		},
		{
			name: "IntExprAdditive",
			pos:  position{line: 176, col: 1, offset: 3572},
			expr: &actionExpr{
				pos: position{line: 176, col: 20, offset: 3591},
				run: (*parser).callonIntExprAdditive1,
				expr: &seqExpr{
					pos: position{line: 176, col: 20, offset: 3591},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 176, col: 20, offset: 3591},
							label: "first",
							expr: &ruleRefExpr{
								pos:  position{line: 176, col: 26, offset: 3597},
								name: "IntExprMultitive",
							},
						},
						&labeledExpr{
							pos:   position{line: 176, col: 43, offset: 3614},
							label: "rest",
							expr: &zeroOrMoreExpr{
								pos: position{line: 176, col: 48, offset: 3619},
								expr: &seqExpr{
									pos: position{line: 176, col: 49, offset: 3620},
									exprs: []interface{}{
										&choiceExpr{
											pos: position{line: 176, col: 50, offset: 3621},
											alternatives: []interface{}{
												&litMatcher{
													pos:        position{line: 176, col: 50, offset: 3621},
													val:        "+",
													ignoreCase: false,
												},
												&litMatcher{
													pos:        position{line: 176, col: 56, offset: 3627},
													val:        "-",
													ignoreCase: false,
												},
											},
										},
										&ruleRefExpr{
											pos:  position{line: 176, col: 61, offset: 3632},
											name: "IntExprMultitive",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "IntExprMultitive",
			pos:  position{line: 180, col: 1, offset: 3701},
			expr: &actionExpr{
				pos: position{line: 180, col: 21, offset: 3721},
				run: (*parser).callonIntExprMultitive1,
				expr: &seqExpr{
					pos: position{line: 180, col: 21, offset: 3721},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 180, col: 21, offset: 3721},
							label: "first",
							expr: &ruleRefExpr{
								pos:  position{line: 180, col: 27, offset: 3727},
								name: "IntExprPrimary",
							},
						},
						&labeledExpr{
							pos:   position{line: 180, col: 42, offset: 3742},
							label: "rest",
							expr: &zeroOrMoreExpr{
								pos: position{line: 180, col: 47, offset: 3747},
								expr: &choiceExpr{
									pos: position{line: 180, col: 48, offset: 3748},
									alternatives: []interface{}{
										&seqExpr{
											pos: position{line: 180, col: 48, offset: 3748},
											exprs: []interface{}{
												&litMatcher{
													pos:        position{line: 180, col: 48, offset: 3748},
													val:        "/",
													ignoreCase: false,
												},
												&ruleRefExpr{
													pos:  position{line: 180, col: 52, offset: 3752},
													name: "IntExprPrimary",
												},
												&charClassMatcher{
													pos:        position{line: 180, col: 67, offset: 3767},
													val:        "[ur]i",
													chars:      []rune{'u', 'r'},
													ignoreCase: true,
													inverted:   false,
												},
											},
										},
										&seqExpr{
											pos: position{line: 180, col: 76, offset: 3776},
											exprs: []interface{}{
												&choiceExpr{
													pos: position{line: 180, col: 77, offset: 3777},
													alternatives: []interface{}{
														&litMatcher{
															pos:        position{line: 180, col: 77, offset: 3777},
															val:        "*",
															ignoreCase: false,
														},
														&litMatcher{
															pos:        position{line: 180, col: 83, offset: 3783},
															val:        "/",
															ignoreCase: false,
														},
													},
												},
												&ruleRefExpr{
													pos:  position{line: 180, col: 88, offset: 3788},
													name: "IntExprPrimary",
												},
											},
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "IntExprPrimary",
			pos:  position{line: 184, col: 1, offset: 3857},
			expr: &choiceExpr{
				pos: position{line: 184, col: 19, offset: 3875},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 184, col: 19, offset: 3875},
						name: "Integer",
					},
					&ruleRefExpr{
						pos:  position{line: 184, col: 29, offset: 3885},
						name: "IntExprUnaryPlus",
					},
					&ruleRefExpr{
						pos:  position{line: 184, col: 48, offset: 3904},
						name: "IntExprUnaryMinus",
					},
					&ruleRefExpr{
						pos:  position{line: 184, col: 68, offset: 3924},
						name: "ParenthesizedIntExpr",
					},
				},
			},
		},
		{
			name: "ParenthesizedIntExpr",
			pos:  position{line: 186, col: 1, offset: 3946},
			expr: &actionExpr{
				pos: position{line: 186, col: 25, offset: 3970},
				run: (*parser).callonParenthesizedIntExpr1,
				expr: &seqExpr{
					pos: position{line: 186, col: 25, offset: 3970},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 186, col: 25, offset: 3970},
							val:        "(",
							ignoreCase: false,
						},
						&labeledExpr{
							pos:   position{line: 186, col: 29, offset: 3974},
							label: "e",
							expr: &ruleRefExpr{
								pos:  position{line: 186, col: 31, offset: 3976},
								name: "IntExpr",
							},
						},
						&litMatcher{
							pos:        position{line: 186, col: 39, offset: 3984},
							val:        ")",
							ignoreCase: false,
						},
					},
				},
			},
		},
		{
			name: "IntExprUnaryPlus",
			pos:  position{line: 190, col: 1, offset: 4019},
			expr: &actionExpr{
				pos: position{line: 190, col: 21, offset: 4039},
				run: (*parser).callonIntExprUnaryPlus1,
				expr: &seqExpr{
					pos: position{line: 190, col: 21, offset: 4039},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 190, col: 21, offset: 4039},
							val:        "+",
							ignoreCase: false,
						},
						&labeledExpr{
							pos:   position{line: 190, col: 25, offset: 4043},
							label: "e",
							expr: &ruleRefExpr{
								pos:  position{line: 190, col: 27, offset: 4045},
								name: "IntExprPrimary",
							},
						},
					},
				},
			},
		},
		{
			name: "IntExprUnaryMinus",
			pos:  position{line: 194, col: 1, offset: 4091},
			expr: &actionExpr{
				pos: position{line: 194, col: 22, offset: 4112},
				run: (*parser).callonIntExprUnaryMinus1,
				expr: &seqExpr{
					pos: position{line: 194, col: 22, offset: 4112},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 194, col: 22, offset: 4112},
							val:        "-",
							ignoreCase: false,
						},
						&labeledExpr{
							pos:   position{line: 194, col: 26, offset: 4116},
							label: "e",
							expr: &ruleRefExpr{
								pos:  position{line: 194, col: 28, offset: 4118},
								name: "IntExprPrimary",
							},
						},
					},
				},
			},
		},
		{
			name: "DRollComp",
			pos:  position{line: 198, col: 1, offset: 4183},
			expr: &actionExpr{
				pos: position{line: 198, col: 14, offset: 4196},
				run: (*parser).callonDRollComp1,
				expr: &seqExpr{
					pos: position{line: 198, col: 14, offset: 4196},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 198, col: 14, offset: 4196},
							label: "left",
							expr: &ruleRefExpr{
								pos:  position{line: 198, col: 19, offset: 4201},
								name: "DRollExprAdditive",
							},
						},
						&labeledExpr{
							pos:   position{line: 198, col: 37, offset: 4219},
							label: "op",
							expr: &ruleRefExpr{
								pos:  position{line: 198, col: 40, offset: 4222},
								name: "CompareOp",
							},
						},
						&labeledExpr{
							pos:   position{line: 198, col: 50, offset: 4232},
							label: "right",
							expr: &ruleRefExpr{
								pos:  position{line: 198, col: 56, offset: 4238},
								name: "IntExpr",
							},
						},
					},
				},
			},
		},
		{
			name: "DRollExpr",
			pos:  position{line: 206, col: 1, offset: 4345},
			expr: &ruleRefExpr{
				pos:  position{line: 206, col: 14, offset: 4358},
				name: "DRollExprAdditive",
			},
		},
		{
			name: "DRollExprAdditive",
			pos:  position{line: 208, col: 1, offset: 4377},
			expr: &actionExpr{
				pos: position{line: 208, col: 22, offset: 4398},
				run: (*parser).callonDRollExprAdditive1,
				expr: &seqExpr{
					pos: position{line: 208, col: 22, offset: 4398},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 208, col: 22, offset: 4398},
							label: "first",
							expr: &ruleRefExpr{
								pos:  position{line: 208, col: 28, offset: 4404},
								name: "DRollExprMultitive",
							},
						},
						&labeledExpr{
							pos:   position{line: 208, col: 47, offset: 4423},
							label: "rest",
							expr: &zeroOrMoreExpr{
								pos: position{line: 208, col: 52, offset: 4428},
								expr: &seqExpr{
									pos: position{line: 208, col: 53, offset: 4429},
									exprs: []interface{}{
										&choiceExpr{
											pos: position{line: 208, col: 54, offset: 4430},
											alternatives: []interface{}{
												&litMatcher{
													pos:        position{line: 208, col: 54, offset: 4430},
													val:        "+",
													ignoreCase: false,
												},
												&litMatcher{
													pos:        position{line: 208, col: 60, offset: 4436},
													val:        "-",
													ignoreCase: false,
												},
											},
										},
										&ruleRefExpr{
											pos:  position{line: 208, col: 65, offset: 4441},
											name: "DRollExprMultitive",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "DRollExprMultitive",
			pos:  position{line: 212, col: 1, offset: 4512},
			expr: &actionExpr{
				pos: position{line: 212, col: 23, offset: 4534},
				run: (*parser).callonDRollExprMultitive1,
				expr: &seqExpr{
					pos: position{line: 212, col: 23, offset: 4534},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 212, col: 23, offset: 4534},
							label: "first",
							expr: &ruleRefExpr{
								pos:  position{line: 212, col: 29, offset: 4540},
								name: "DRollExprPrimary",
							},
						},
						&labeledExpr{
							pos:   position{line: 212, col: 46, offset: 4557},
							label: "rest",
							expr: &zeroOrMoreExpr{
								pos: position{line: 212, col: 51, offset: 4562},
								expr: &choiceExpr{
									pos: position{line: 212, col: 52, offset: 4563},
									alternatives: []interface{}{
										&seqExpr{
											pos: position{line: 212, col: 52, offset: 4563},
											exprs: []interface{}{
												&litMatcher{
													pos:        position{line: 212, col: 52, offset: 4563},
													val:        "/",
													ignoreCase: false,
												},
												&ruleRefExpr{
													pos:  position{line: 212, col: 56, offset: 4567},
													name: "DRollExprPrimary",
												},
												&charClassMatcher{
													pos:        position{line: 212, col: 73, offset: 4584},
													val:        "[ur]i",
													chars:      []rune{'u', 'r'},
													ignoreCase: true,
													inverted:   false,
												},
											},
										},
										&seqExpr{
											pos: position{line: 212, col: 82, offset: 4593},
											exprs: []interface{}{
												&choiceExpr{
													pos: position{line: 212, col: 83, offset: 4594},
													alternatives: []interface{}{
														&litMatcher{
															pos:        position{line: 212, col: 83, offset: 4594},
															val:        "*",
															ignoreCase: false,
														},
														&litMatcher{
															pos:        position{line: 212, col: 89, offset: 4600},
															val:        "/",
															ignoreCase: false,
														},
													},
												},
												&ruleRefExpr{
													pos:  position{line: 212, col: 94, offset: 4605},
													name: "DRollExprPrimary",
												},
											},
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "DRollExprPrimary",
			pos:  position{line: 216, col: 1, offset: 4676},
			expr: &choiceExpr{
				pos: position{line: 216, col: 21, offset: 4696},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 216, col: 21, offset: 4696},
						name: "DRoll",
					},
					&ruleRefExpr{
						pos:  position{line: 216, col: 29, offset: 4704},
						name: "Rand",
					},
					&ruleRefExpr{
						pos:  position{line: 216, col: 36, offset: 4711},
						name: "Integer",
					},
					&ruleRefExpr{
						pos:  position{line: 216, col: 46, offset: 4721},
						name: "DRollExprUnaryPlus",
					},
					&ruleRefExpr{
						pos:  position{line: 216, col: 67, offset: 4742},
						name: "DRollExprUnaryMinus",
					},
					&ruleRefExpr{
						pos:  position{line: 216, col: 89, offset: 4764},
						name: "ParenthesizedDRollExpr",
					},
				},
			},
		},
		{
			name: "ParenthesizedDRollExpr",
			pos:  position{line: 218, col: 1, offset: 4788},
			expr: &actionExpr{
				pos: position{line: 218, col: 27, offset: 4814},
				run: (*parser).callonParenthesizedDRollExpr1,
				expr: &seqExpr{
					pos: position{line: 218, col: 27, offset: 4814},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 218, col: 27, offset: 4814},
							val:        "(",
							ignoreCase: false,
						},
						&labeledExpr{
							pos:   position{line: 218, col: 31, offset: 4818},
							label: "e",
							expr: &ruleRefExpr{
								pos:  position{line: 218, col: 33, offset: 4820},
								name: "DRollExpr",
							},
						},
						&litMatcher{
							pos:        position{line: 218, col: 43, offset: 4830},
							val:        ")",
							ignoreCase: false,
						},
					},
				},
			},
		},
		{
			name: "DRollExprUnaryPlus",
			pos:  position{line: 222, col: 1, offset: 4865},
			expr: &actionExpr{
				pos: position{line: 222, col: 23, offset: 4887},
				run: (*parser).callonDRollExprUnaryPlus1,
				expr: &seqExpr{
					pos: position{line: 222, col: 23, offset: 4887},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 222, col: 23, offset: 4887},
							val:        "+",
							ignoreCase: false,
						},
						&labeledExpr{
							pos:   position{line: 222, col: 27, offset: 4891},
							label: "e",
							expr: &ruleRefExpr{
								pos:  position{line: 222, col: 29, offset: 4893},
								name: "DRollExprPrimary",
							},
						},
					},
				},
			},
		},
		{
			name: "DRollExprUnaryMinus",
			pos:  position{line: 226, col: 1, offset: 4941},
			expr: &actionExpr{
				pos: position{line: 226, col: 24, offset: 4964},
				run: (*parser).callonDRollExprUnaryMinus1,
				expr: &seqExpr{
					pos: position{line: 226, col: 24, offset: 4964},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 226, col: 24, offset: 4964},
							val:        "-",
							ignoreCase: false,
						},
						&labeledExpr{
							pos:   position{line: 226, col: 28, offset: 4968},
							label: "e",
							expr: &ruleRefExpr{
								pos:  position{line: 226, col: 30, offset: 4970},
								name: "DRollExprPrimary",
							},
						},
					},
				},
			},
		},
		{
			name: "IntRandExpr",
			pos:  position{line: 230, col: 1, offset: 5037},
			expr: &ruleRefExpr{
				pos:  position{line: 230, col: 16, offset: 5052},
				name: "IntRandExprAdditive",
			},
		},
		{
			name: "IntRandExprAdditive",
			pos:  position{line: 232, col: 1, offset: 5073},
			expr: &actionExpr{
				pos: position{line: 232, col: 24, offset: 5096},
				run: (*parser).callonIntRandExprAdditive1,
				expr: &seqExpr{
					pos: position{line: 232, col: 24, offset: 5096},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 232, col: 24, offset: 5096},
							label: "first",
							expr: &ruleRefExpr{
								pos:  position{line: 232, col: 30, offset: 5102},
								name: "IntRandExprMultitive",
							},
						},
						&labeledExpr{
							pos:   position{line: 232, col: 51, offset: 5123},
							label: "rest",
							expr: &zeroOrMoreExpr{
								pos: position{line: 232, col: 56, offset: 5128},
								expr: &seqExpr{
									pos: position{line: 232, col: 57, offset: 5129},
									exprs: []interface{}{
										&choiceExpr{
											pos: position{line: 232, col: 58, offset: 5130},
											alternatives: []interface{}{
												&litMatcher{
													pos:        position{line: 232, col: 58, offset: 5130},
													val:        "+",
													ignoreCase: false,
												},
												&litMatcher{
													pos:        position{line: 232, col: 64, offset: 5136},
													val:        "-",
													ignoreCase: false,
												},
											},
										},
										&ruleRefExpr{
											pos:  position{line: 232, col: 69, offset: 5141},
											name: "IntRandExprMultitive",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "IntRandExprMultitive",
			pos:  position{line: 236, col: 1, offset: 5214},
			expr: &actionExpr{
				pos: position{line: 236, col: 25, offset: 5238},
				run: (*parser).callonIntRandExprMultitive1,
				expr: &seqExpr{
					pos: position{line: 236, col: 25, offset: 5238},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 236, col: 25, offset: 5238},
							label: "first",
							expr: &ruleRefExpr{
								pos:  position{line: 236, col: 31, offset: 5244},
								name: "IntRandExprPrimary",
							},
						},
						&labeledExpr{
							pos:   position{line: 236, col: 50, offset: 5263},
							label: "rest",
							expr: &zeroOrMoreExpr{
								pos: position{line: 236, col: 55, offset: 5268},
								expr: &choiceExpr{
									pos: position{line: 236, col: 56, offset: 5269},
									alternatives: []interface{}{
										&seqExpr{
											pos: position{line: 236, col: 56, offset: 5269},
											exprs: []interface{}{
												&litMatcher{
													pos:        position{line: 236, col: 56, offset: 5269},
													val:        "/",
													ignoreCase: false,
												},
												&ruleRefExpr{
													pos:  position{line: 236, col: 60, offset: 5273},
													name: "IntRandExprPrimary",
												},
												&charClassMatcher{
													pos:        position{line: 236, col: 79, offset: 5292},
													val:        "[ur]i",
													chars:      []rune{'u', 'r'},
													ignoreCase: true,
													inverted:   false,
												},
											},
										},
										&seqExpr{
											pos: position{line: 236, col: 88, offset: 5301},
											exprs: []interface{}{
												&choiceExpr{
													pos: position{line: 236, col: 89, offset: 5302},
													alternatives: []interface{}{
														&litMatcher{
															pos:        position{line: 236, col: 89, offset: 5302},
															val:        "*",
															ignoreCase: false,
														},
														&litMatcher{
															pos:        position{line: 236, col: 95, offset: 5308},
															val:        "/",
															ignoreCase: false,
														},
													},
												},
												&ruleRefExpr{
													pos:  position{line: 236, col: 100, offset: 5313},
													name: "IntRandExprPrimary",
												},
											},
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "IntRandExprPrimary",
			pos:  position{line: 240, col: 1, offset: 5386},
			expr: &choiceExpr{
				pos: position{line: 240, col: 23, offset: 5408},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 240, col: 23, offset: 5408},
						name: "Integer",
					},
					&ruleRefExpr{
						pos:  position{line: 240, col: 33, offset: 5418},
						name: "Rand",
					},
					&ruleRefExpr{
						pos:  position{line: 240, col: 40, offset: 5425},
						name: "IntRandExprUnaryPlus",
					},
					&ruleRefExpr{
						pos:  position{line: 240, col: 63, offset: 5448},
						name: "IntRandExprUnaryMinus",
					},
					&ruleRefExpr{
						pos:  position{line: 240, col: 87, offset: 5472},
						name: "ParenthesizedIntRandExpr",
					},
				},
			},
		},
		{
			name: "ParenthesizedIntRandExpr",
			pos:  position{line: 242, col: 1, offset: 5498},
			expr: &actionExpr{
				pos: position{line: 242, col: 29, offset: 5526},
				run: (*parser).callonParenthesizedIntRandExpr1,
				expr: &seqExpr{
					pos: position{line: 242, col: 29, offset: 5526},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 242, col: 29, offset: 5526},
							val:        "(",
							ignoreCase: false,
						},
						&labeledExpr{
							pos:   position{line: 242, col: 33, offset: 5530},
							label: "e",
							expr: &ruleRefExpr{
								pos:  position{line: 242, col: 35, offset: 5532},
								name: "IntRandExpr",
							},
						},
						&litMatcher{
							pos:        position{line: 242, col: 47, offset: 5544},
							val:        ")",
							ignoreCase: false,
						},
					},
				},
			},
		},
		{
			name: "IntRandExprUnaryPlus",
			pos:  position{line: 246, col: 1, offset: 5579},
			expr: &actionExpr{
				pos: position{line: 246, col: 25, offset: 5603},
				run: (*parser).callonIntRandExprUnaryPlus1,
				expr: &seqExpr{
					pos: position{line: 246, col: 25, offset: 5603},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 246, col: 25, offset: 5603},
							val:        "+",
							ignoreCase: false,
						},
						&labeledExpr{
							pos:   position{line: 246, col: 29, offset: 5607},
							label: "e",
							expr: &ruleRefExpr{
								pos:  position{line: 246, col: 31, offset: 5609},
								name: "IntRandExprPrimary",
							},
						},
					},
				},
			},
		},
		{
			name: "IntRandExprUnaryMinus",
			pos:  position{line: 250, col: 1, offset: 5659},
			expr: &actionExpr{
				pos: position{line: 250, col: 26, offset: 5684},
				run: (*parser).callonIntRandExprUnaryMinus1,
				expr: &seqExpr{
					pos: position{line: 250, col: 26, offset: 5684},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 250, col: 26, offset: 5684},
							val:        "-",
							ignoreCase: false,
						},
						&labeledExpr{
							pos:   position{line: 250, col: 30, offset: 5688},
							label: "e",
							expr: &ruleRefExpr{
								pos:  position{line: 250, col: 32, offset: 5690},
								name: "IntRandExprPrimary",
							},
						},
					},
				},
			},
		},
		{
			name: "DRoll",
			pos:  position{line: 254, col: 1, offset: 5759},
			expr: &actionExpr{
				pos: position{line: 254, col: 10, offset: 5768},
				run: (*parser).callonDRoll1,
				expr: &seqExpr{
					pos: position{line: 254, col: 10, offset: 5768},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 254, col: 10, offset: 5768},
							label: "num",
							expr: &ruleRefExpr{
								pos:  position{line: 254, col: 14, offset: 5772},
								name: "RollOperand",
							},
						},
						&litMatcher{
							pos:        position{line: 254, col: 26, offset: 5784},
							val:        "d",
							ignoreCase: true,
						},
						&labeledExpr{
							pos:   position{line: 254, col: 31, offset: 5789},
							label: "sides",
							expr: &ruleRefExpr{
								pos:  position{line: 254, col: 37, offset: 5795},
								name: "RollOperand",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 254, col: 49, offset: 5807},
							name: "IncRandCount",
						},
					},
				},
			},
		},
		{
			name: "BRoll",
			pos:  position{line: 261, col: 1, offset: 5930},
			expr: &actionExpr{
				pos: position{line: 261, col: 10, offset: 5939},
				run: (*parser).callonBRoll1,
				expr: &seqExpr{
					pos: position{line: 261, col: 10, offset: 5939},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 261, col: 10, offset: 5939},
							label: "num",
							expr: &ruleRefExpr{
								pos:  position{line: 261, col: 14, offset: 5943},
								name: "RollOperand",
							},
						},
						&litMatcher{
							pos:        position{line: 261, col: 26, offset: 5955},
							val:        "b",
							ignoreCase: true,
						},
						&labeledExpr{
							pos:   position{line: 261, col: 31, offset: 5960},
							label: "sides",
							expr: &ruleRefExpr{
								pos:  position{line: 261, col: 37, offset: 5966},
								name: "RollOperand",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 261, col: 49, offset: 5978},
							name: "IncRandCount",
						},
					},
				},
			},
		},
		{
			name: "RRoll",
			pos:  position{line: 268, col: 1, offset: 6101},
			expr: &actionExpr{
				pos: position{line: 268, col: 10, offset: 6110},
				run: (*parser).callonRRoll1,
				expr: &seqExpr{
					pos: position{line: 268, col: 10, offset: 6110},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 268, col: 10, offset: 6110},
							label: "num",
							expr: &ruleRefExpr{
								pos:  position{line: 268, col: 14, offset: 6114},
								name: "RollOperand",
							},
						},
						&litMatcher{
							pos:        position{line: 268, col: 26, offset: 6126},
							val:        "r",
							ignoreCase: true,
						},
						&labeledExpr{
							pos:   position{line: 268, col: 31, offset: 6131},
							label: "sides",
							expr: &ruleRefExpr{
								pos:  position{line: 268, col: 37, offset: 6137},
								name: "RollOperand",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 268, col: 49, offset: 6149},
							name: "IncRandCount",
						},
					},
				},
			},
		},
		{
			name: "RollOperand",
			pos:  position{line: 275, col: 1, offset: 6272},
			expr: &choiceExpr{
				pos: position{line: 275, col: 16, offset: 6287},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 275, col: 16, offset: 6287},
						name: "Integer",
					},
					&ruleRefExpr{
						pos:  position{line: 275, col: 26, offset: 6297},
						name: "Rand",
					},
					&ruleRefExpr{
						pos:  position{line: 275, col: 33, offset: 6304},
						name: "ParenthesizedIntRandExpr",
					},
				},
			},
		},
		{
			name: "Rand",
			pos:  position{line: 277, col: 1, offset: 6330},
			expr: &actionExpr{
				pos: position{line: 277, col: 9, offset: 6338},
				run: (*parser).callonRand1,
				expr: &seqExpr{
					pos: position{line: 277, col: 9, offset: 6338},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 277, col: 9, offset: 6338},
							val:        "[",
							ignoreCase: false,
						},
						&labeledExpr{
							pos:   position{line: 277, col: 13, offset: 6342},
							label: "min",
							expr: &ruleRefExpr{
								pos:  position{line: 277, col: 17, offset: 6346},
								name: "RandOperand",
							},
						},
						&litMatcher{
							pos:        position{line: 277, col: 29, offset: 6358},
							val:        "...",
							ignoreCase: false,
						},
						&labeledExpr{
							pos:   position{line: 277, col: 35, offset: 6364},
							label: "max",
							expr: &ruleRefExpr{
								pos:  position{line: 277, col: 39, offset: 6368},
								name: "RandOperand",
							},
						},
						&litMatcher{
							pos:        position{line: 277, col: 51, offset: 6380},
							val:        "]",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 277, col: 55, offset: 6384},
							name: "IncRandCount",
						},
					},
				},
			},
		},
		{
			name: "RandOperand",
			pos:  position{line: 284, col: 1, offset: 6508},
			expr: &choiceExpr{
				pos: position{line: 284, col: 16, offset: 6523},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 284, col: 16, offset: 6523},
						name: "Integer",
					},
					&ruleRefExpr{
						pos:  position{line: 284, col: 26, offset: 6533},
						name: "ParenthesizedIntExpr",
					},
				},
			},
		},
		{
			name: "ResetRandCount",
			pos:  position{line: 286, col: 1, offset: 6555},
			expr: &stateCodeExpr{
				pos: position{line: 286, col: 19, offset: 6573},
				run: (*parser).callonResetRandCount1,
			},
		},
		{
			name: "IncRandCount",
			pos:  position{line: 291, col: 1, offset: 6617},
			expr: &stateCodeExpr{
				pos: position{line: 291, col: 17, offset: 6633},
				run: (*parser).callonIncRandCount1,
			},
		},
		{
			name: "Integer",
			pos:  position{line: 296, col: 1, offset: 6706},
			expr: &actionExpr{
				pos: position{line: 296, col: 12, offset: 6717},
				run: (*parser).callonInteger1,
				expr: &oneOrMoreExpr{
					pos: position{line: 296, col: 12, offset: 6717},
					expr: &charClassMatcher{
						pos:        position{line: 296, col: 12, offset: 6717},
						val:        "[0-9]",
						ranges:     []rune{'0', '9'},
						ignoreCase: false,
						inverted:   false,
					},
				},
			},
		},
		{
			name: "CompareOp",
			pos:  position{line: 305, col: 1, offset: 6886},
			expr: &choiceExpr{
				pos: position{line: 305, col: 14, offset: 6899},
				alternatives: []interface{}{
					&litMatcher{
						pos:        position{line: 305, col: 14, offset: 6899},
						val:        "=",
						ignoreCase: false,
					},
					&litMatcher{
						pos:        position{line: 305, col: 20, offset: 6905},
						val:        "<>",
						ignoreCase: false,
					},
					&litMatcher{
						pos:        position{line: 305, col: 27, offset: 6912},
						val:        "<=",
						ignoreCase: false,
					},
					&litMatcher{
						pos:        position{line: 305, col: 34, offset: 6919},
						val:        "<",
						ignoreCase: false,
					},
					&litMatcher{
						pos:        position{line: 305, col: 40, offset: 6925},
						val:        ">=",
						ignoreCase: false,
					},
					&litMatcher{
						pos:        position{line: 305, col: 47, offset: 6932},
						val:        ">",
						ignoreCase: false,
					},
				},
			},
		},
		{
			name: "EOT",
			pos:  position{line: 307, col: 1, offset: 6937},
			expr: &notExpr{
				pos: position{line: 307, col: 8, offset: 6944},
				expr: &anyMatcher{
					line: 307, col: 9, offset: 6945,
				},
			},
		},
	},
}

func (c *current) onCommand1(n interface{}) (interface{}, error) {
	return n, nil
}

func (p *parser) callonCommand1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCommand1(stack["n"])
}

func (c *current) onCommandWithExpression1(n interface{}) (interface{}, error) {
	return n, nil
}

func (p *parser) callonCommandWithExpression1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCommandWithExpression1(stack["n"])
}

func (c *current) onChoice1(items interface{}) (interface{}, error) {
	return items, nil
}

func (p *parser) callonChoice1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onChoice1(stack["items"])
}

func (c *current) onChoiceItems1(first, rest interface{}) (interface{}, error) {
	firstString := first.(*ast.String)
	choice := ast.NewChoice(firstString)

	for _, r := range toIfaceSlice(rest) {
		rs := toIfaceSlice(r)
		i := rs[1].(*ast.String)

		choice.Append(i)
	}

	return choice, nil
}

func (p *parser) callonChoiceItems1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onChoiceItems1(stack["first"], stack["rest"])
}

func (c *current) onChoiceItem1(s interface{}) (interface{}, error) {
	return s, nil
}

func (p *parser) callonChoiceItem1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onChoiceItem1(stack["s"])
}

func (c *current) onChoiceItemChars1() (interface{}, error) {
	return ast.NewString(strings.TrimSpace(string(c.text))), nil
}

func (p *parser) callonChoiceItemChars1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onChoiceItemChars1()
}

func (c *current) onCalc1(expr interface{}) (interface{}, error) {
	return ast.NewCalc(expr.(ast.Node)), nil
}

func (p *parser) callonCalc1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCalc1(stack["expr"])
}

func (c *current) onDRollExprCommand1(expr interface{}) (interface{}, error) {
	if c.state["RandCount"].(int) < 1 {
		return nil, fmt.Errorf("random element not found")
	}

	return ast.NewDRollExpr(expr.(ast.Node)), nil
}

func (p *parser) callonDRollExprCommand1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDRollExprCommand1(stack["expr"])
}

func (c *current) onDRollCompCommand1(expr interface{}) (interface{}, error) {
	if c.state["RandCount"].(int) < 1 {
		return nil, fmt.Errorf("random element not found")
	}

	return ast.NewDRollComp(expr.(ast.Node)), nil
}

func (p *parser) callonDRollCompCommand1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDRollCompCommand1(stack["expr"])
}

func (c *current) onBRollList1(first, rest interface{}) (interface{}, error) {
	bRollList := ast.NewBRollList(first.(*ast.BRoll))

	for _, r := range toIfaceSlice(rest) {
		rs := toIfaceSlice(r)
		b := rs[1].(*ast.BRoll)
		bRollList.Append(b)
	}

	return bRollList, nil
}

func (p *parser) callonBRollList1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onBRollList1(stack["first"], stack["rest"])
}

func (c *current) onBRollComp1(left, op, right interface{}) (interface{}, error) {
	return ast.NewBRollComp(
		ast.NewCompare(
			left.(ast.Node),
			string(op.([]byte)),
			right.(ast.Node),
		),
	), nil
}

func (p *parser) callonBRollComp1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onBRollComp1(stack["left"], stack["op"], stack["right"])
}

func (c *current) onRRollList1(first, rest, th interface{}) (interface{}, error) {
	ths := toIfaceSlice(th)

	var threshold ast.Node = ast.NilInstance()
	if ths != nil {
		threshold = ths[1].(ast.Node)
	}

	rRollList := ast.NewRRollList(first.(*ast.RRoll), threshold)

	for _, r := range toIfaceSlice(rest) {
		rs := toIfaceSlice(r)
		rr := rs[1].(*ast.RRoll)
		rRollList.Append(rr)
	}

	return rRollList, nil
}

func (p *parser) callonRRollList1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onRRollList1(stack["first"], stack["rest"], stack["th"])
}

func (c *current) onRRollComp1(left, op, right interface{}) (interface{}, error) {
	return ast.NewRRollComp(
		ast.NewCompare(
			left.(ast.Node),
			string(op.([]byte)),
			right.(ast.Node),
		),
	), nil
}

func (p *parser) callonRRollComp1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onRRollComp1(stack["left"], stack["op"], stack["right"])
}

func (c *current) onIntExprAdditive1(first, rest interface{}) (interface{}, error) {
	return leftAssociativeAdditive(first, rest)
}

func (p *parser) callonIntExprAdditive1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onIntExprAdditive1(stack["first"], stack["rest"])
}

func (c *current) onIntExprMultitive1(first, rest interface{}) (interface{}, error) {
	return leftAssociativeMultitive(first, rest)
}

func (p *parser) callonIntExprMultitive1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onIntExprMultitive1(stack["first"], stack["rest"])
}

func (c *current) onParenthesizedIntExpr1(e interface{}) (interface{}, error) {
	return e.(ast.Node), nil
}

func (p *parser) callonParenthesizedIntExpr1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onParenthesizedIntExpr1(stack["e"])
}

func (c *current) onIntExprUnaryPlus1(e interface{}) (interface{}, error) {
	return e.(ast.Node), nil
}

func (p *parser) callonIntExprUnaryPlus1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onIntExprUnaryPlus1(stack["e"])
}

func (c *current) onIntExprUnaryMinus1(e interface{}) (interface{}, error) {
	return ast.NewUnaryMinus(e.(ast.Node)), nil
}

func (p *parser) callonIntExprUnaryMinus1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onIntExprUnaryMinus1(stack["e"])
}

func (c *current) onDRollComp1(left, op, right interface{}) (interface{}, error) {
	return ast.NewCompare(
		left.(ast.Node),
		string(op.([]byte)),
		right.(ast.Node),
	), nil
}

func (p *parser) callonDRollComp1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDRollComp1(stack["left"], stack["op"], stack["right"])
}

func (c *current) onDRollExprAdditive1(first, rest interface{}) (interface{}, error) {
	return leftAssociativeAdditive(first, rest)
}

func (p *parser) callonDRollExprAdditive1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDRollExprAdditive1(stack["first"], stack["rest"])
}

func (c *current) onDRollExprMultitive1(first, rest interface{}) (interface{}, error) {
	return leftAssociativeMultitive(first, rest)
}

func (p *parser) callonDRollExprMultitive1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDRollExprMultitive1(stack["first"], stack["rest"])
}

func (c *current) onParenthesizedDRollExpr1(e interface{}) (interface{}, error) {
	return e.(ast.Node), nil
}

func (p *parser) callonParenthesizedDRollExpr1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onParenthesizedDRollExpr1(stack["e"])
}

func (c *current) onDRollExprUnaryPlus1(e interface{}) (interface{}, error) {
	return e.(ast.Node), nil
}

func (p *parser) callonDRollExprUnaryPlus1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDRollExprUnaryPlus1(stack["e"])
}

func (c *current) onDRollExprUnaryMinus1(e interface{}) (interface{}, error) {
	return ast.NewUnaryMinus(e.(ast.Node)), nil
}

func (p *parser) callonDRollExprUnaryMinus1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDRollExprUnaryMinus1(stack["e"])
}

func (c *current) onIntRandExprAdditive1(first, rest interface{}) (interface{}, error) {
	return leftAssociativeAdditive(first, rest)
}

func (p *parser) callonIntRandExprAdditive1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onIntRandExprAdditive1(stack["first"], stack["rest"])
}

func (c *current) onIntRandExprMultitive1(first, rest interface{}) (interface{}, error) {
	return leftAssociativeMultitive(first, rest)
}

func (p *parser) callonIntRandExprMultitive1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onIntRandExprMultitive1(stack["first"], stack["rest"])
}

func (c *current) onParenthesizedIntRandExpr1(e interface{}) (interface{}, error) {
	return e.(ast.Node), nil
}

func (p *parser) callonParenthesizedIntRandExpr1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onParenthesizedIntRandExpr1(stack["e"])
}

func (c *current) onIntRandExprUnaryPlus1(e interface{}) (interface{}, error) {
	return e.(ast.Node), nil
}

func (p *parser) callonIntRandExprUnaryPlus1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onIntRandExprUnaryPlus1(stack["e"])
}

func (c *current) onIntRandExprUnaryMinus1(e interface{}) (interface{}, error) {
	return ast.NewUnaryMinus(e.(ast.Node)), nil
}

func (p *parser) callonIntRandExprUnaryMinus1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onIntRandExprUnaryMinus1(stack["e"])
}

func (c *current) onDRoll1(num, sides interface{}) (interface{}, error) {
	numNode := num.(ast.Node)
	sidesNode := sides.(ast.Node)

	return ast.NewDRoll(numNode, sidesNode), nil
}

func (p *parser) callonDRoll1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDRoll1(stack["num"], stack["sides"])
}

func (c *current) onBRoll1(num, sides interface{}) (interface{}, error) {
	numNode := num.(ast.Node)
	sidesNode := sides.(ast.Node)

	return ast.NewBRoll(numNode, sidesNode), nil
}

func (p *parser) callonBRoll1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onBRoll1(stack["num"], stack["sides"])
}

func (c *current) onRRoll1(num, sides interface{}) (interface{}, error) {
	numNode := num.(ast.Node)
	sidesNode := sides.(ast.Node)

	return ast.NewRRoll(numNode, sidesNode), nil
}

func (p *parser) callonRRoll1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onRRoll1(stack["num"], stack["sides"])
}

func (c *current) onRand1(min, max interface{}) (interface{}, error) {
	minNode := min.(ast.Node)
	maxNode := max.(ast.Node)

	return ast.NewRandomNumber(minNode, maxNode), nil
}

func (p *parser) callonRand1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onRand1(stack["min"], stack["max"])
}

func (c *current) onResetRandCount1() error {
	c.state["RandCount"] = 0
	return nil
}

func (p *parser) callonResetRandCount1() error {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onResetRandCount1()
}

func (c *current) onIncRandCount1() error {
	c.state["RandCount"] = c.state["RandCount"].(int) + 1
	return nil
}

func (p *parser) callonIncRandCount1() error {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onIncRandCount1()
}

func (c *current) onInteger1() (interface{}, error) {
	s := string(c.text)

	// TODO: 整数が大きすぎるときなどのエラー処理が必要
	value, _ := strconv.Atoi(s)

	return ast.NewInt(value), nil
}

func (p *parser) callonInteger1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onInteger1()
}

var (
	// errNoRule is returned when the grammar to parse has no rule.
	errNoRule = errors.New("grammar has no rule")

	// errInvalidEntrypoint is returned when the specified entrypoint rule
	// does not exit.
	errInvalidEntrypoint = errors.New("invalid entrypoint")

	// errInvalidEncoding is returned when the source is not properly
	// utf8-encoded.
	errInvalidEncoding = errors.New("invalid encoding")

	// errMaxExprCnt is used to signal that the maximum number of
	// expressions have been parsed.
	errMaxExprCnt = errors.New("max number of expresssions parsed")
)

// Option is a function that can set an option on the parser. It returns
// the previous setting as an Option.
type Option func(*parser) Option

// MaxExpressions creates an Option to stop parsing after the provided
// number of expressions have been parsed, if the value is 0 then the parser will
// parse for as many steps as needed (possibly an infinite number).
//
// The default for maxExprCnt is 0.
func MaxExpressions(maxExprCnt uint64) Option {
	return func(p *parser) Option {
		oldMaxExprCnt := p.maxExprCnt
		p.maxExprCnt = maxExprCnt
		return MaxExpressions(oldMaxExprCnt)
	}
}

// Entrypoint creates an Option to set the rule name to use as entrypoint.
// The rule name must have been specified in the -alternate-entrypoints
// if generating the parser with the -optimize-grammar flag, otherwise
// it may have been optimized out. Passing an empty string sets the
// entrypoint to the first rule in the grammar.
//
// The default is to start parsing at the first rule in the grammar.
func Entrypoint(ruleName string) Option {
	return func(p *parser) Option {
		oldEntrypoint := p.entrypoint
		p.entrypoint = ruleName
		if ruleName == "" {
			p.entrypoint = g.rules[0].name
		}
		return Entrypoint(oldEntrypoint)
	}
}

// Statistics adds a user provided Stats struct to the parser to allow
// the user to process the results after the parsing has finished.
// Also the key for the "no match" counter is set.
//
// Example usage:
//
//     input := "input"
//     stats := Stats{}
//     _, err := Parse("input-file", []byte(input), Statistics(&stats, "no match"))
//     if err != nil {
//         log.Panicln(err)
//     }
//     b, err := json.MarshalIndent(stats.ChoiceAltCnt, "", "  ")
//     if err != nil {
//         log.Panicln(err)
//     }
//     fmt.Println(string(b))
//
func Statistics(stats *Stats, choiceNoMatch string) Option {
	return func(p *parser) Option {
		oldStats := p.Stats
		p.Stats = stats
		oldChoiceNoMatch := p.choiceNoMatch
		p.choiceNoMatch = choiceNoMatch
		if p.Stats.ChoiceAltCnt == nil {
			p.Stats.ChoiceAltCnt = make(map[string]map[string]int)
		}
		return Statistics(oldStats, oldChoiceNoMatch)
	}
}

// Debug creates an Option to set the debug flag to b. When set to true,
// debugging information is printed to stdout while parsing.
//
// The default is false.
func Debug(b bool) Option {
	return func(p *parser) Option {
		old := p.debug
		p.debug = b
		return Debug(old)
	}
}

// Memoize creates an Option to set the memoize flag to b. When set to true,
// the parser will cache all results so each expression is evaluated only
// once. This guarantees linear parsing time even for pathological cases,
// at the expense of more memory and slower times for typical cases.
//
// The default is false.
func Memoize(b bool) Option {
	return func(p *parser) Option {
		old := p.memoize
		p.memoize = b
		return Memoize(old)
	}
}

// AllowInvalidUTF8 creates an Option to allow invalid UTF-8 bytes.
// Every invalid UTF-8 byte is treated as a utf8.RuneError (U+FFFD)
// by character class matchers and is matched by the any matcher.
// The returned matched value, c.text and c.offset are NOT affected.
//
// The default is false.
func AllowInvalidUTF8(b bool) Option {
	return func(p *parser) Option {
		old := p.allowInvalidUTF8
		p.allowInvalidUTF8 = b
		return AllowInvalidUTF8(old)
	}
}

// Recover creates an Option to set the recover flag to b. When set to
// true, this causes the parser to recover from panics and convert it
// to an error. Setting it to false can be useful while debugging to
// access the full stack trace.
//
// The default is true.
func Recover(b bool) Option {
	return func(p *parser) Option {
		old := p.recover
		p.recover = b
		return Recover(old)
	}
}

// GlobalStore creates an Option to set a key to a certain value in
// the globalStore.
func GlobalStore(key string, value interface{}) Option {
	return func(p *parser) Option {
		old := p.cur.globalStore[key]
		p.cur.globalStore[key] = value
		return GlobalStore(key, old)
	}
}

// InitState creates an Option to set a key to a certain value in
// the global "state" store.
func InitState(key string, value interface{}) Option {
	return func(p *parser) Option {
		old := p.cur.state[key]
		p.cur.state[key] = value
		return InitState(key, old)
	}
}

// ParseFile parses the file identified by filename.
func ParseFile(filename string, opts ...Option) (i interface{}, err error) {
	f, err := os.Open(filename)
	if err != nil {
		return nil, err
	}
	defer func() {
		if closeErr := f.Close(); closeErr != nil {
			err = closeErr
		}
	}()
	return ParseReader(filename, f, opts...)
}

// ParseReader parses the data from r using filename as information in the
// error messages.
func ParseReader(filename string, r io.Reader, opts ...Option) (interface{}, error) {
	b, err := ioutil.ReadAll(r)
	if err != nil {
		return nil, err
	}

	return Parse(filename, b, opts...)
}

// Parse parses the data from b using filename as information in the
// error messages.
func Parse(filename string, b []byte, opts ...Option) (interface{}, error) {
	return newParser(filename, b, opts...).parse(g)
}

// position records a position in the text.
type position struct {
	line, col, offset int
}

func (p position) String() string {
	return strconv.Itoa(p.line) + ":" + strconv.Itoa(p.col) + " [" + strconv.Itoa(p.offset) + "]"
}

// savepoint stores all state required to go back to this point in the
// parser.
type savepoint struct {
	position
	rn rune
	w  int
}

type current struct {
	pos  position // start position of the match
	text []byte   // raw text of the match

	// state is a store for arbitrary key,value pairs that the user wants to be
	// tied to the backtracking of the parser.
	// This is always rolled back if a parsing rule fails.
	state storeDict

	// globalStore is a general store for the user to store arbitrary key-value
	// pairs that they need to manage and that they do not want tied to the
	// backtracking of the parser. This is only modified by the user and never
	// rolled back by the parser. It is always up to the user to keep this in a
	// consistent state.
	globalStore storeDict
}

type storeDict map[string]interface{}

// the AST types...

type grammar struct {
	pos   position
	rules []*rule
}

type rule struct {
	pos         position
	name        string
	displayName string
	expr        interface{}
}

type choiceExpr struct {
	pos          position
	alternatives []interface{}
}

type actionExpr struct {
	pos  position
	expr interface{}
	run  func(*parser) (interface{}, error)
}

type recoveryExpr struct {
	pos          position
	expr         interface{}
	recoverExpr  interface{}
	failureLabel []string
}

type seqExpr struct {
	pos   position
	exprs []interface{}
}

type throwExpr struct {
	pos   position
	label string
}

type labeledExpr struct {
	pos   position
	label string
	expr  interface{}
}

type expr struct {
	pos  position
	expr interface{}
}

type andExpr expr
type notExpr expr
type zeroOrOneExpr expr
type zeroOrMoreExpr expr
type oneOrMoreExpr expr

type ruleRefExpr struct {
	pos  position
	name string
}

type stateCodeExpr struct {
	pos position
	run func(*parser) error
}

type andCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type notCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type litMatcher struct {
	pos        position
	val        string
	ignoreCase bool
}

type charClassMatcher struct {
	pos             position
	val             string
	basicLatinChars [128]bool
	chars           []rune
	ranges          []rune
	classes         []*unicode.RangeTable
	ignoreCase      bool
	inverted        bool
}

type anyMatcher position

// errList cumulates the errors found by the parser.
type errList []error

func (e *errList) add(err error) {
	*e = append(*e, err)
}

func (e errList) err() error {
	if len(e) == 0 {
		return nil
	}
	e.dedupe()
	return e
}

func (e *errList) dedupe() {
	var cleaned []error
	set := make(map[string]bool)
	for _, err := range *e {
		if msg := err.Error(); !set[msg] {
			set[msg] = true
			cleaned = append(cleaned, err)
		}
	}
	*e = cleaned
}

func (e errList) Error() string {
	switch len(e) {
	case 0:
		return ""
	case 1:
		return e[0].Error()
	default:
		var buf bytes.Buffer

		for i, err := range e {
			if i > 0 {
				buf.WriteRune('\n')
			}
			buf.WriteString(err.Error())
		}
		return buf.String()
	}
}

// parserError wraps an error with a prefix indicating the rule in which
// the error occurred. The original error is stored in the Inner field.
type parserError struct {
	Inner    error
	pos      position
	prefix   string
	expected []string
}

// Error returns the error message.
func (p *parserError) Error() string {
	return p.prefix + ": " + p.Inner.Error()
}

// newParser creates a parser with the specified input source and options.
func newParser(filename string, b []byte, opts ...Option) *parser {
	stats := Stats{
		ChoiceAltCnt: make(map[string]map[string]int),
	}

	p := &parser{
		filename: filename,
		errs:     new(errList),
		data:     b,
		pt:       savepoint{position: position{line: 1}},
		recover:  true,
		cur: current{
			state:       make(storeDict),
			globalStore: make(storeDict),
		},
		maxFailPos:      position{col: 1, line: 1},
		maxFailExpected: make([]string, 0, 20),
		Stats:           &stats,
		// start rule is rule [0] unless an alternate entrypoint is specified
		entrypoint: g.rules[0].name,
	}
	p.setOptions(opts)

	if p.maxExprCnt == 0 {
		p.maxExprCnt = math.MaxUint64
	}

	return p
}

// setOptions applies the options to the parser.
func (p *parser) setOptions(opts []Option) {
	for _, opt := range opts {
		opt(p)
	}
}

type resultTuple struct {
	v   interface{}
	b   bool
	end savepoint
}

const choiceNoMatch = -1

// Stats stores some statistics, gathered during parsing
type Stats struct {
	// ExprCnt counts the number of expressions processed during parsing
	// This value is compared to the maximum number of expressions allowed
	// (set by the MaxExpressions option).
	ExprCnt uint64

	// ChoiceAltCnt is used to count for each ordered choice expression,
	// which alternative is used how may times.
	// These numbers allow to optimize the order of the ordered choice expression
	// to increase the performance of the parser
	//
	// The outer key of ChoiceAltCnt is composed of the name of the rule as well
	// as the line and the column of the ordered choice.
	// The inner key of ChoiceAltCnt is the number (one-based) of the matching alternative.
	// For each alternative the number of matches are counted. If an ordered choice does not
	// match, a special counter is incremented. The name of this counter is set with
	// the parser option Statistics.
	// For an alternative to be included in ChoiceAltCnt, it has to match at least once.
	ChoiceAltCnt map[string]map[string]int
}

type parser struct {
	filename string
	pt       savepoint
	cur      current

	data []byte
	errs *errList

	depth   int
	recover bool
	debug   bool

	memoize bool
	// memoization table for the packrat algorithm:
	// map[offset in source] map[expression or rule] {value, match}
	memo map[int]map[interface{}]resultTuple

	// rules table, maps the rule identifier to the rule node
	rules map[string]*rule
	// variables stack, map of label to value
	vstack []map[string]interface{}
	// rule stack, allows identification of the current rule in errors
	rstack []*rule

	// parse fail
	maxFailPos            position
	maxFailExpected       []string
	maxFailInvertExpected bool

	// max number of expressions to be parsed
	maxExprCnt uint64
	// entrypoint for the parser
	entrypoint string

	allowInvalidUTF8 bool

	*Stats

	choiceNoMatch string
	// recovery expression stack, keeps track of the currently available recovery expression, these are traversed in reverse
	recoveryStack []map[string]interface{}
}

// push a variable set on the vstack.
func (p *parser) pushV() {
	if cap(p.vstack) == len(p.vstack) {
		// create new empty slot in the stack
		p.vstack = append(p.vstack, nil)
	} else {
		// slice to 1 more
		p.vstack = p.vstack[:len(p.vstack)+1]
	}

	// get the last args set
	m := p.vstack[len(p.vstack)-1]
	if m != nil && len(m) == 0 {
		// empty map, all good
		return
	}

	m = make(map[string]interface{})
	p.vstack[len(p.vstack)-1] = m
}

// pop a variable set from the vstack.
func (p *parser) popV() {
	// if the map is not empty, clear it
	m := p.vstack[len(p.vstack)-1]
	if len(m) > 0 {
		// GC that map
		p.vstack[len(p.vstack)-1] = nil
	}
	p.vstack = p.vstack[:len(p.vstack)-1]
}

// push a recovery expression with its labels to the recoveryStack
func (p *parser) pushRecovery(labels []string, expr interface{}) {
	if cap(p.recoveryStack) == len(p.recoveryStack) {
		// create new empty slot in the stack
		p.recoveryStack = append(p.recoveryStack, nil)
	} else {
		// slice to 1 more
		p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)+1]
	}

	m := make(map[string]interface{}, len(labels))
	for _, fl := range labels {
		m[fl] = expr
	}
	p.recoveryStack[len(p.recoveryStack)-1] = m
}

// pop a recovery expression from the recoveryStack
func (p *parser) popRecovery() {
	// GC that map
	p.recoveryStack[len(p.recoveryStack)-1] = nil

	p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)-1]
}

func (p *parser) print(prefix, s string) string {
	if !p.debug {
		return s
	}

	fmt.Printf("%s %d:%d:%d: %s [%#U]\n",
		prefix, p.pt.line, p.pt.col, p.pt.offset, s, p.pt.rn)
	return s
}

func (p *parser) in(s string) string {
	p.depth++
	return p.print(strings.Repeat(" ", p.depth)+">", s)
}

func (p *parser) out(s string) string {
	p.depth--
	return p.print(strings.Repeat(" ", p.depth)+"<", s)
}

func (p *parser) addErr(err error) {
	p.addErrAt(err, p.pt.position, []string{})
}

func (p *parser) addErrAt(err error, pos position, expected []string) {
	var buf bytes.Buffer
	if p.filename != "" {
		buf.WriteString(p.filename)
	}
	if buf.Len() > 0 {
		buf.WriteString(":")
	}
	buf.WriteString(fmt.Sprintf("%d:%d (%d)", pos.line, pos.col, pos.offset))
	if len(p.rstack) > 0 {
		if buf.Len() > 0 {
			buf.WriteString(": ")
		}
		rule := p.rstack[len(p.rstack)-1]
		if rule.displayName != "" {
			buf.WriteString("rule " + rule.displayName)
		} else {
			buf.WriteString("rule " + rule.name)
		}
	}
	pe := &parserError{Inner: err, pos: pos, prefix: buf.String(), expected: expected}
	p.errs.add(pe)
}

func (p *parser) failAt(fail bool, pos position, want string) {
	// process fail if parsing fails and not inverted or parsing succeeds and invert is set
	if fail == p.maxFailInvertExpected {
		if pos.offset < p.maxFailPos.offset {
			return
		}

		if pos.offset > p.maxFailPos.offset {
			p.maxFailPos = pos
			p.maxFailExpected = p.maxFailExpected[:0]
		}

		if p.maxFailInvertExpected {
			want = "!" + want
		}
		p.maxFailExpected = append(p.maxFailExpected, want)
	}
}

// read advances the parser to the next rune.
func (p *parser) read() {
	p.pt.offset += p.pt.w
	rn, n := utf8.DecodeRune(p.data[p.pt.offset:])
	p.pt.rn = rn
	p.pt.w = n
	p.pt.col++
	if rn == '\n' {
		p.pt.line++
		p.pt.col = 0
	}

	if rn == utf8.RuneError && n == 1 { // see utf8.DecodeRune
		if !p.allowInvalidUTF8 {
			p.addErr(errInvalidEncoding)
		}
	}
}

// restore parser position to the savepoint pt.
func (p *parser) restore(pt savepoint) {
	if p.debug {
		defer p.out(p.in("restore"))
	}
	if pt.offset == p.pt.offset {
		return
	}
	p.pt = pt
}

// Cloner is implemented by any value that has a Clone method, which returns a
// copy of the value. This is mainly used for types which are not passed by
// value (e.g map, slice, chan) or structs that contain such types.
//
// This is used in conjunction with the global state feature to create proper
// copies of the state to allow the parser to properly restore the state in
// the case of backtracking.
type Cloner interface {
	Clone() interface{}
}

var statePool = &sync.Pool{
	New: func() interface{} { return make(storeDict) },
}

func (sd storeDict) Discard() {
	for k := range sd {
		delete(sd, k)
	}
	statePool.Put(sd)
}

// clone and return parser current state.
func (p *parser) cloneState() storeDict {
	if p.debug {
		defer p.out(p.in("cloneState"))
	}

	state := statePool.Get().(storeDict)
	for k, v := range p.cur.state {
		if c, ok := v.(Cloner); ok {
			state[k] = c.Clone()
		} else {
			state[k] = v
		}
	}
	return state
}

// restore parser current state to the state storeDict.
// every restoreState should applied only one time for every cloned state
func (p *parser) restoreState(state storeDict) {
	if p.debug {
		defer p.out(p.in("restoreState"))
	}
	p.cur.state.Discard()
	p.cur.state = state
}

// get the slice of bytes from the savepoint start to the current position.
func (p *parser) sliceFrom(start savepoint) []byte {
	return p.data[start.position.offset:p.pt.position.offset]
}

func (p *parser) getMemoized(node interface{}) (resultTuple, bool) {
	if len(p.memo) == 0 {
		return resultTuple{}, false
	}
	m := p.memo[p.pt.offset]
	if len(m) == 0 {
		return resultTuple{}, false
	}
	res, ok := m[node]
	return res, ok
}

func (p *parser) setMemoized(pt savepoint, node interface{}, tuple resultTuple) {
	if p.memo == nil {
		p.memo = make(map[int]map[interface{}]resultTuple)
	}
	m := p.memo[pt.offset]
	if m == nil {
		m = make(map[interface{}]resultTuple)
		p.memo[pt.offset] = m
	}
	m[node] = tuple
}

func (p *parser) buildRulesTable(g *grammar) {
	p.rules = make(map[string]*rule, len(g.rules))
	for _, r := range g.rules {
		p.rules[r.name] = r
	}
}

func (p *parser) parse(g *grammar) (val interface{}, err error) {
	if len(g.rules) == 0 {
		p.addErr(errNoRule)
		return nil, p.errs.err()
	}

	// TODO : not super critical but this could be generated
	p.buildRulesTable(g)

	if p.recover {
		// panic can be used in action code to stop parsing immediately
		// and return the panic as an error.
		defer func() {
			if e := recover(); e != nil {
				if p.debug {
					defer p.out(p.in("panic handler"))
				}
				val = nil
				switch e := e.(type) {
				case error:
					p.addErr(e)
				default:
					p.addErr(fmt.Errorf("%v", e))
				}
				err = p.errs.err()
			}
		}()
	}

	startRule, ok := p.rules[p.entrypoint]
	if !ok {
		p.addErr(errInvalidEntrypoint)
		return nil, p.errs.err()
	}

	p.read() // advance to first rune
	val, ok = p.parseRule(startRule)
	if !ok {
		if len(*p.errs) == 0 {
			// If parsing fails, but no errors have been recorded, the expected values
			// for the farthest parser position are returned as error.
			maxFailExpectedMap := make(map[string]struct{}, len(p.maxFailExpected))
			for _, v := range p.maxFailExpected {
				maxFailExpectedMap[v] = struct{}{}
			}
			expected := make([]string, 0, len(maxFailExpectedMap))
			eof := false
			if _, ok := maxFailExpectedMap["!."]; ok {
				delete(maxFailExpectedMap, "!.")
				eof = true
			}
			for k := range maxFailExpectedMap {
				expected = append(expected, k)
			}
			sort.Strings(expected)
			if eof {
				expected = append(expected, "EOF")
			}
			p.addErrAt(errors.New("no match found, expected: "+listJoin(expected, ", ", "or")), p.maxFailPos, expected)
		}

		return nil, p.errs.err()
	}
	return val, p.errs.err()
}

func listJoin(list []string, sep string, lastSep string) string {
	switch len(list) {
	case 0:
		return ""
	case 1:
		return list[0]
	default:
		return strings.Join(list[:len(list)-1], sep) + " " + lastSep + " " + list[len(list)-1]
	}
}

func (p *parser) parseRule(rule *rule) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRule " + rule.name))
	}

	if p.memoize {
		res, ok := p.getMemoized(rule)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
	}

	start := p.pt
	p.rstack = append(p.rstack, rule)
	p.pushV()
	val, ok := p.parseExpr(rule.expr)
	p.popV()
	p.rstack = p.rstack[:len(p.rstack)-1]
	if ok && p.debug {
		p.print(strings.Repeat(" ", p.depth)+"MATCH", string(p.sliceFrom(start)))
	}

	if p.memoize {
		p.setMemoized(start, rule, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseExpr(expr interface{}) (interface{}, bool) {
	var pt savepoint

	if p.memoize {
		res, ok := p.getMemoized(expr)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
		pt = p.pt
	}

	p.ExprCnt++
	if p.ExprCnt > p.maxExprCnt {
		panic(errMaxExprCnt)
	}

	var val interface{}
	var ok bool
	switch expr := expr.(type) {
	case *actionExpr:
		val, ok = p.parseActionExpr(expr)
	case *andCodeExpr:
		val, ok = p.parseAndCodeExpr(expr)
	case *andExpr:
		val, ok = p.parseAndExpr(expr)
	case *anyMatcher:
		val, ok = p.parseAnyMatcher(expr)
	case *charClassMatcher:
		val, ok = p.parseCharClassMatcher(expr)
	case *choiceExpr:
		val, ok = p.parseChoiceExpr(expr)
	case *labeledExpr:
		val, ok = p.parseLabeledExpr(expr)
	case *litMatcher:
		val, ok = p.parseLitMatcher(expr)
	case *notCodeExpr:
		val, ok = p.parseNotCodeExpr(expr)
	case *notExpr:
		val, ok = p.parseNotExpr(expr)
	case *oneOrMoreExpr:
		val, ok = p.parseOneOrMoreExpr(expr)
	case *recoveryExpr:
		val, ok = p.parseRecoveryExpr(expr)
	case *ruleRefExpr:
		val, ok = p.parseRuleRefExpr(expr)
	case *seqExpr:
		val, ok = p.parseSeqExpr(expr)
	case *stateCodeExpr:
		val, ok = p.parseStateCodeExpr(expr)
	case *throwExpr:
		val, ok = p.parseThrowExpr(expr)
	case *zeroOrMoreExpr:
		val, ok = p.parseZeroOrMoreExpr(expr)
	case *zeroOrOneExpr:
		val, ok = p.parseZeroOrOneExpr(expr)
	default:
		panic(fmt.Sprintf("unknown expression type %T", expr))
	}
	if p.memoize {
		p.setMemoized(pt, expr, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseActionExpr(act *actionExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseActionExpr"))
	}

	start := p.pt
	val, ok := p.parseExpr(act.expr)
	if ok {
		p.cur.pos = start.position
		p.cur.text = p.sliceFrom(start)
		state := p.cloneState()
		actVal, err := act.run(p)
		if err != nil {
			p.addErrAt(err, start.position, []string{})
		}
		p.restoreState(state)

		val = actVal
	}
	if ok && p.debug {
		p.print(strings.Repeat(" ", p.depth)+"MATCH", string(p.sliceFrom(start)))
	}
	return val, ok
}

func (p *parser) parseAndCodeExpr(and *andCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAndCodeExpr"))
	}

	state := p.cloneState()

	ok, err := and.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, ok
}

func (p *parser) parseAndExpr(and *andExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAndExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	_, ok := p.parseExpr(and.expr)
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, ok
}

func (p *parser) parseAnyMatcher(any *anyMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAnyMatcher"))
	}

	if p.pt.rn == utf8.RuneError && p.pt.w == 0 {
		// EOF - see utf8.DecodeRune
		p.failAt(false, p.pt.position, ".")
		return nil, false
	}
	start := p.pt
	p.read()
	p.failAt(true, start.position, ".")
	return p.sliceFrom(start), true
}

func (p *parser) parseCharClassMatcher(chr *charClassMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseCharClassMatcher"))
	}

	cur := p.pt.rn
	start := p.pt

	// can't match EOF
	if cur == utf8.RuneError && p.pt.w == 0 { // see utf8.DecodeRune
		p.failAt(false, start.position, chr.val)
		return nil, false
	}

	if chr.ignoreCase {
		cur = unicode.ToLower(cur)
	}

	// try to match in the list of available chars
	for _, rn := range chr.chars {
		if rn == cur {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of ranges
	for i := 0; i < len(chr.ranges); i += 2 {
		if cur >= chr.ranges[i] && cur <= chr.ranges[i+1] {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of Unicode classes
	for _, cl := range chr.classes {
		if unicode.Is(cl, cur) {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	if chr.inverted {
		p.read()
		p.failAt(true, start.position, chr.val)
		return p.sliceFrom(start), true
	}
	p.failAt(false, start.position, chr.val)
	return nil, false
}

func (p *parser) incChoiceAltCnt(ch *choiceExpr, altI int) {
	choiceIdent := fmt.Sprintf("%s %d:%d", p.rstack[len(p.rstack)-1].name, ch.pos.line, ch.pos.col)
	m := p.ChoiceAltCnt[choiceIdent]
	if m == nil {
		m = make(map[string]int)
		p.ChoiceAltCnt[choiceIdent] = m
	}
	// We increment altI by 1, so the keys do not start at 0
	alt := strconv.Itoa(altI + 1)
	if altI == choiceNoMatch {
		alt = p.choiceNoMatch
	}
	m[alt]++
}

func (p *parser) parseChoiceExpr(ch *choiceExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseChoiceExpr"))
	}

	for altI, alt := range ch.alternatives {
		// dummy assignment to prevent compile error if optimized
		_ = altI

		state := p.cloneState()

		p.pushV()
		val, ok := p.parseExpr(alt)
		p.popV()
		if ok {
			p.incChoiceAltCnt(ch, altI)
			return val, ok
		}
		p.restoreState(state)
	}
	p.incChoiceAltCnt(ch, choiceNoMatch)
	return nil, false
}

func (p *parser) parseLabeledExpr(lab *labeledExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseLabeledExpr"))
	}

	p.pushV()
	val, ok := p.parseExpr(lab.expr)
	p.popV()
	if ok && lab.label != "" {
		m := p.vstack[len(p.vstack)-1]
		m[lab.label] = val
	}
	return val, ok
}

func (p *parser) parseLitMatcher(lit *litMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseLitMatcher"))
	}

	ignoreCase := ""
	if lit.ignoreCase {
		ignoreCase = "i"
	}
	val := string(strconv.AppendQuote([]byte{}, lit.val)) + ignoreCase // wrap 'lit.val' with double quotes
	start := p.pt
	for _, want := range lit.val {
		cur := p.pt.rn
		if lit.ignoreCase {
			cur = unicode.ToLower(cur)
		}
		if cur != want {
			p.failAt(false, start.position, val)
			p.restore(start)
			return nil, false
		}
		p.read()
	}
	p.failAt(true, start.position, val)
	return p.sliceFrom(start), true
}

func (p *parser) parseNotCodeExpr(not *notCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseNotCodeExpr"))
	}

	state := p.cloneState()

	ok, err := not.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, !ok
}

func (p *parser) parseNotExpr(not *notExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseNotExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	_, ok := p.parseExpr(not.expr)
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, !ok
}

func (p *parser) parseOneOrMoreExpr(expr *oneOrMoreExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseOneOrMoreExpr"))
	}

	var vals []interface{}

	for {
		p.pushV()
		val, ok := p.parseExpr(expr.expr)
		p.popV()
		if !ok {
			if len(vals) == 0 {
				// did not match once, no match
				return nil, false
			}
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseRecoveryExpr(recover *recoveryExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRecoveryExpr (" + strings.Join(recover.failureLabel, ",") + ")"))
	}

	p.pushRecovery(recover.failureLabel, recover.recoverExpr)
	val, ok := p.parseExpr(recover.expr)
	p.popRecovery()

	return val, ok
}

func (p *parser) parseRuleRefExpr(ref *ruleRefExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRuleRefExpr " + ref.name))
	}

	if ref.name == "" {
		panic(fmt.Sprintf("%s: invalid rule: missing name", ref.pos))
	}

	rule := p.rules[ref.name]
	if rule == nil {
		p.addErr(fmt.Errorf("undefined rule: %s", ref.name))
		return nil, false
	}
	return p.parseRule(rule)
}

func (p *parser) parseSeqExpr(seq *seqExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseSeqExpr"))
	}

	vals := make([]interface{}, 0, len(seq.exprs))

	pt := p.pt
	state := p.cloneState()
	for _, expr := range seq.exprs {
		val, ok := p.parseExpr(expr)
		if !ok {
			p.restoreState(state)
			p.restore(pt)
			return nil, false
		}
		vals = append(vals, val)
	}
	return vals, true
}

func (p *parser) parseStateCodeExpr(state *stateCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseStateCodeExpr"))
	}

	err := state.run(p)
	if err != nil {
		p.addErr(err)
	}
	return nil, true
}

func (p *parser) parseThrowExpr(expr *throwExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseThrowExpr"))
	}

	for i := len(p.recoveryStack) - 1; i >= 0; i-- {
		if recoverExpr, ok := p.recoveryStack[i][expr.label]; ok {
			if val, ok := p.parseExpr(recoverExpr); ok {
				return val, ok
			}
		}
	}

	return nil, false
}

func (p *parser) parseZeroOrMoreExpr(expr *zeroOrMoreExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrMoreExpr"))
	}

	var vals []interface{}

	for {
		p.pushV()
		val, ok := p.parseExpr(expr.expr)
		p.popV()
		if !ok {
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseZeroOrOneExpr(expr *zeroOrOneExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrOneExpr"))
	}

	p.pushV()
	val, _ := p.parseExpr(expr.expr)
	p.popV()
	// whether it matched or not, consider it a match
	return val, true
}

func rangeTable(class string) *unicode.RangeTable {
	if rt, ok := unicode.Categories[class]; ok {
		return rt
	}
	if rt, ok := unicode.Properties[class]; ok {
		return rt
	}
	if rt, ok := unicode.Scripts[class]; ok {
		return rt
	}

	// cannot happen
	panic(fmt.Sprintf("invalid Unicode class: %s", class))
}
