// Code generated by pigeon; DO NOT EDIT.

package peg_parser

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"io/ioutil"
	"math"
	"os"
	"sort"
	"strconv"
	"strings"
	"unicode"
	"unicode/utf8"

	"github.com/raa0121/GoBCDice/pkg/core/ast"
)

func leftAssociativeAdditive(first interface{}, rest interface{}) (ast.Node, error) {
	lastNode := first.(ast.Node)
	for _, r := range rest.([]interface{}) {
		rs := r.([]interface{})
		op := string(rs[0].([]byte))
		right := rs[1].(ast.Node)

		switch op {
		case "+":
			lastNode = ast.NewAdd2(lastNode, right)
		case "-":
			lastNode = ast.NewSubtract2(lastNode, right)
		}
	}

	return lastNode, nil
}

func leftAssociativeMultitive(first interface{}, rest interface{}) (ast.Node, error) {
	lastNode := first.(ast.Node)
	for _, r := range rest.([]interface{}) {
		rs := r.([]interface{})
		op := string(rs[0].([]byte))
		right := rs[1].(ast.Node)

		roundingMethod := ""
		if len(rs) >= 3 {
			roundingMethod = strings.ToUpper(string(rs[2].([]byte)))
		}

		switch op {
		case "*":
			lastNode = ast.NewMultiply2(lastNode, right)
		case "/":
			switch roundingMethod {
			case "U":
				lastNode = ast.NewDivideWithRoundingUp2(lastNode, right)
			case "R":
				lastNode = ast.NewDivideWithRounding2(lastNode, right)
			case "":
				lastNode = ast.NewDivideWithRoundingDown2(lastNode, right)
			}
		}
	}

	return lastNode, nil
}

var g = &grammar{
	rules: []*rule{
		{
			name: "Command",
			pos:  position{line: 62, col: 1, offset: 1281},
			expr: &actionExpr{
				pos: position{line: 62, col: 12, offset: 1292},
				run: (*parser).callonCommand1,
				expr: &seqExpr{
					pos: position{line: 62, col: 12, offset: 1292},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 62, col: 12, offset: 1292},
							label: "n",
							expr: &choiceExpr{
								pos: position{line: 62, col: 15, offset: 1295},
								alternatives: []interface{}{
									&ruleRefExpr{
										pos:  position{line: 62, col: 15, offset: 1295},
										name: "Calc",
									},
									&ruleRefExpr{
										pos:  position{line: 62, col: 22, offset: 1302},
										name: "DRollExprCommand",
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 62, col: 40, offset: 1320},
							name: "EOT",
						},
					},
				},
			},
		},
		{
			name: "Calc",
			pos:  position{line: 66, col: 1, offset: 1344},
			expr: &actionExpr{
				pos: position{line: 66, col: 9, offset: 1352},
				run: (*parser).callonCalc1,
				expr: &seqExpr{
					pos: position{line: 66, col: 9, offset: 1352},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 66, col: 9, offset: 1352},
							label: "calc",
							expr: &litMatcher{
								pos:        position{line: 66, col: 14, offset: 1357},
								val:        "c",
								ignoreCase: true,
							},
						},
						&litMatcher{
							pos:        position{line: 66, col: 19, offset: 1362},
							val:        "(",
							ignoreCase: false,
						},
						&labeledExpr{
							pos:   position{line: 66, col: 23, offset: 1366},
							label: "expr",
							expr: &ruleRefExpr{
								pos:  position{line: 66, col: 28, offset: 1371},
								name: "IntExpr",
							},
						},
						&litMatcher{
							pos:        position{line: 66, col: 36, offset: 1379},
							val:        ")",
							ignoreCase: false,
						},
					},
				},
			},
		},
		{
			name: "DRollExprCommand",
			pos:  position{line: 70, col: 1, offset: 1431},
			expr: &actionExpr{
				pos: position{line: 70, col: 21, offset: 1451},
				run: (*parser).callonDRollExprCommand1,
				expr: &seqExpr{
					pos: position{line: 70, col: 21, offset: 1451},
					exprs: []interface{}{
						&stateCodeExpr{
							pos: position{line: 70, col: 21, offset: 1451},
							run: (*parser).callonDRollExprCommand3,
						},
						&labeledExpr{
							pos:   position{line: 73, col: 3, offset: 1494},
							label: "expr",
							expr: &ruleRefExpr{
								pos:  position{line: 73, col: 8, offset: 1499},
								name: "DRollExpr",
							},
						},
					},
				},
			},
		},
		{
			name: "IntExpr",
			pos:  position{line: 81, col: 1, offset: 1656},
			expr: &ruleRefExpr{
				pos:  position{line: 81, col: 12, offset: 1667},
				name: "IntExprAdditive",
			},
		},
		{
			name: "IntExprAdditive",
			pos:  position{line: 83, col: 1, offset: 1684},
			expr: &actionExpr{
				pos: position{line: 83, col: 20, offset: 1703},
				run: (*parser).callonIntExprAdditive1,
				expr: &seqExpr{
					pos: position{line: 83, col: 20, offset: 1703},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 83, col: 20, offset: 1703},
							label: "first",
							expr: &ruleRefExpr{
								pos:  position{line: 83, col: 26, offset: 1709},
								name: "IntExprMultitive",
							},
						},
						&labeledExpr{
							pos:   position{line: 83, col: 43, offset: 1726},
							label: "rest",
							expr: &zeroOrMoreExpr{
								pos: position{line: 83, col: 48, offset: 1731},
								expr: &seqExpr{
									pos: position{line: 83, col: 49, offset: 1732},
									exprs: []interface{}{
										&choiceExpr{
											pos: position{line: 83, col: 50, offset: 1733},
											alternatives: []interface{}{
												&litMatcher{
													pos:        position{line: 83, col: 50, offset: 1733},
													val:        "+",
													ignoreCase: false,
												},
												&litMatcher{
													pos:        position{line: 83, col: 56, offset: 1739},
													val:        "-",
													ignoreCase: false,
												},
											},
										},
										&ruleRefExpr{
											pos:  position{line: 83, col: 61, offset: 1744},
											name: "IntExprMultitive",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "IntExprMultitive",
			pos:  position{line: 87, col: 1, offset: 1813},
			expr: &actionExpr{
				pos: position{line: 87, col: 21, offset: 1833},
				run: (*parser).callonIntExprMultitive1,
				expr: &seqExpr{
					pos: position{line: 87, col: 21, offset: 1833},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 87, col: 21, offset: 1833},
							label: "first",
							expr: &ruleRefExpr{
								pos:  position{line: 87, col: 27, offset: 1839},
								name: "IntExprPrimary",
							},
						},
						&labeledExpr{
							pos:   position{line: 87, col: 42, offset: 1854},
							label: "rest",
							expr: &zeroOrMoreExpr{
								pos: position{line: 87, col: 47, offset: 1859},
								expr: &choiceExpr{
									pos: position{line: 87, col: 48, offset: 1860},
									alternatives: []interface{}{
										&seqExpr{
											pos: position{line: 87, col: 48, offset: 1860},
											exprs: []interface{}{
												&litMatcher{
													pos:        position{line: 87, col: 48, offset: 1860},
													val:        "/",
													ignoreCase: false,
												},
												&ruleRefExpr{
													pos:  position{line: 87, col: 52, offset: 1864},
													name: "IntExprPrimary",
												},
												&charClassMatcher{
													pos:        position{line: 87, col: 67, offset: 1879},
													val:        "[ur]i",
													chars:      []rune{'u', 'r'},
													ignoreCase: true,
													inverted:   false,
												},
											},
										},
										&seqExpr{
											pos: position{line: 87, col: 76, offset: 1888},
											exprs: []interface{}{
												&choiceExpr{
													pos: position{line: 87, col: 77, offset: 1889},
													alternatives: []interface{}{
														&litMatcher{
															pos:        position{line: 87, col: 77, offset: 1889},
															val:        "*",
															ignoreCase: false,
														},
														&litMatcher{
															pos:        position{line: 87, col: 83, offset: 1895},
															val:        "/",
															ignoreCase: false,
														},
													},
												},
												&ruleRefExpr{
													pos:  position{line: 87, col: 88, offset: 1900},
													name: "IntExprPrimary",
												},
											},
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "IntExprPrimary",
			pos:  position{line: 91, col: 1, offset: 1969},
			expr: &choiceExpr{
				pos: position{line: 91, col: 19, offset: 1987},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 91, col: 19, offset: 1987},
						name: "Integer",
					},
					&ruleRefExpr{
						pos:  position{line: 91, col: 29, offset: 1997},
						name: "IntExprUnaryPlus",
					},
					&ruleRefExpr{
						pos:  position{line: 91, col: 48, offset: 2016},
						name: "IntExprUnaryMinus",
					},
					&ruleRefExpr{
						pos:  position{line: 91, col: 68, offset: 2036},
						name: "ParenthesizedIntExpr",
					},
				},
			},
		},
		{
			name: "ParenthesizedIntExpr",
			pos:  position{line: 93, col: 1, offset: 2058},
			expr: &actionExpr{
				pos: position{line: 93, col: 25, offset: 2082},
				run: (*parser).callonParenthesizedIntExpr1,
				expr: &seqExpr{
					pos: position{line: 93, col: 25, offset: 2082},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 93, col: 25, offset: 2082},
							val:        "(",
							ignoreCase: false,
						},
						&labeledExpr{
							pos:   position{line: 93, col: 29, offset: 2086},
							label: "e",
							expr: &ruleRefExpr{
								pos:  position{line: 93, col: 31, offset: 2088},
								name: "IntExpr",
							},
						},
						&litMatcher{
							pos:        position{line: 93, col: 39, offset: 2096},
							val:        ")",
							ignoreCase: false,
						},
					},
				},
			},
		},
		{
			name: "IntExprUnaryPlus",
			pos:  position{line: 97, col: 1, offset: 2131},
			expr: &actionExpr{
				pos: position{line: 97, col: 21, offset: 2151},
				run: (*parser).callonIntExprUnaryPlus1,
				expr: &seqExpr{
					pos: position{line: 97, col: 21, offset: 2151},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 97, col: 21, offset: 2151},
							val:        "+",
							ignoreCase: false,
						},
						&labeledExpr{
							pos:   position{line: 97, col: 25, offset: 2155},
							label: "e",
							expr: &ruleRefExpr{
								pos:  position{line: 97, col: 27, offset: 2157},
								name: "IntExprPrimary",
							},
						},
					},
				},
			},
		},
		{
			name: "IntExprUnaryMinus",
			pos:  position{line: 101, col: 1, offset: 2203},
			expr: &actionExpr{
				pos: position{line: 101, col: 22, offset: 2224},
				run: (*parser).callonIntExprUnaryMinus1,
				expr: &seqExpr{
					pos: position{line: 101, col: 22, offset: 2224},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 101, col: 22, offset: 2224},
							val:        "-",
							ignoreCase: false,
						},
						&labeledExpr{
							pos:   position{line: 101, col: 26, offset: 2228},
							label: "e",
							expr: &ruleRefExpr{
								pos:  position{line: 101, col: 28, offset: 2230},
								name: "IntExprPrimary",
							},
						},
					},
				},
			},
		},
		{
			name: "DRollExpr",
			pos:  position{line: 105, col: 1, offset: 2296},
			expr: &ruleRefExpr{
				pos:  position{line: 105, col: 14, offset: 2309},
				name: "DRollExprAdditive",
			},
		},
		{
			name: "DRollExprAdditive",
			pos:  position{line: 107, col: 1, offset: 2328},
			expr: &actionExpr{
				pos: position{line: 107, col: 22, offset: 2349},
				run: (*parser).callonDRollExprAdditive1,
				expr: &seqExpr{
					pos: position{line: 107, col: 22, offset: 2349},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 107, col: 22, offset: 2349},
							label: "first",
							expr: &ruleRefExpr{
								pos:  position{line: 107, col: 28, offset: 2355},
								name: "DRollExprMultitive",
							},
						},
						&labeledExpr{
							pos:   position{line: 107, col: 47, offset: 2374},
							label: "rest",
							expr: &zeroOrMoreExpr{
								pos: position{line: 107, col: 52, offset: 2379},
								expr: &seqExpr{
									pos: position{line: 107, col: 53, offset: 2380},
									exprs: []interface{}{
										&choiceExpr{
											pos: position{line: 107, col: 54, offset: 2381},
											alternatives: []interface{}{
												&litMatcher{
													pos:        position{line: 107, col: 54, offset: 2381},
													val:        "+",
													ignoreCase: false,
												},
												&litMatcher{
													pos:        position{line: 107, col: 60, offset: 2387},
													val:        "-",
													ignoreCase: false,
												},
											},
										},
										&ruleRefExpr{
											pos:  position{line: 107, col: 65, offset: 2392},
											name: "DRollExprMultitive",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "DRollExprMultitive",
			pos:  position{line: 111, col: 1, offset: 2463},
			expr: &actionExpr{
				pos: position{line: 111, col: 23, offset: 2485},
				run: (*parser).callonDRollExprMultitive1,
				expr: &seqExpr{
					pos: position{line: 111, col: 23, offset: 2485},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 111, col: 23, offset: 2485},
							label: "first",
							expr: &ruleRefExpr{
								pos:  position{line: 111, col: 29, offset: 2491},
								name: "DRollExprPrimary",
							},
						},
						&labeledExpr{
							pos:   position{line: 111, col: 46, offset: 2508},
							label: "rest",
							expr: &zeroOrMoreExpr{
								pos: position{line: 111, col: 51, offset: 2513},
								expr: &choiceExpr{
									pos: position{line: 111, col: 52, offset: 2514},
									alternatives: []interface{}{
										&seqExpr{
											pos: position{line: 111, col: 52, offset: 2514},
											exprs: []interface{}{
												&litMatcher{
													pos:        position{line: 111, col: 52, offset: 2514},
													val:        "/",
													ignoreCase: false,
												},
												&ruleRefExpr{
													pos:  position{line: 111, col: 56, offset: 2518},
													name: "DRollExprPrimary",
												},
												&charClassMatcher{
													pos:        position{line: 111, col: 73, offset: 2535},
													val:        "[ur]i",
													chars:      []rune{'u', 'r'},
													ignoreCase: true,
													inverted:   false,
												},
											},
										},
										&seqExpr{
											pos: position{line: 111, col: 82, offset: 2544},
											exprs: []interface{}{
												&choiceExpr{
													pos: position{line: 111, col: 83, offset: 2545},
													alternatives: []interface{}{
														&litMatcher{
															pos:        position{line: 111, col: 83, offset: 2545},
															val:        "*",
															ignoreCase: false,
														},
														&litMatcher{
															pos:        position{line: 111, col: 89, offset: 2551},
															val:        "/",
															ignoreCase: false,
														},
													},
												},
												&ruleRefExpr{
													pos:  position{line: 111, col: 94, offset: 2556},
													name: "DRollExprPrimary",
												},
											},
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "DRollExprPrimary",
			pos:  position{line: 115, col: 1, offset: 2627},
			expr: &choiceExpr{
				pos: position{line: 115, col: 21, offset: 2647},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 115, col: 21, offset: 2647},
						name: "DRoll",
					},
					&ruleRefExpr{
						pos:  position{line: 115, col: 29, offset: 2655},
						name: "Rand",
					},
					&ruleRefExpr{
						pos:  position{line: 115, col: 36, offset: 2662},
						name: "Integer",
					},
					&ruleRefExpr{
						pos:  position{line: 115, col: 46, offset: 2672},
						name: "DRollExprUnaryPlus",
					},
					&ruleRefExpr{
						pos:  position{line: 115, col: 67, offset: 2693},
						name: "DRollExprUnaryMinus",
					},
					&ruleRefExpr{
						pos:  position{line: 115, col: 89, offset: 2715},
						name: "ParenthesizedDRollExpr",
					},
				},
			},
		},
		{
			name: "ParenthesizedDRollExpr",
			pos:  position{line: 117, col: 1, offset: 2739},
			expr: &actionExpr{
				pos: position{line: 117, col: 27, offset: 2765},
				run: (*parser).callonParenthesizedDRollExpr1,
				expr: &seqExpr{
					pos: position{line: 117, col: 27, offset: 2765},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 117, col: 27, offset: 2765},
							val:        "(",
							ignoreCase: false,
						},
						&labeledExpr{
							pos:   position{line: 117, col: 31, offset: 2769},
							label: "e",
							expr: &ruleRefExpr{
								pos:  position{line: 117, col: 33, offset: 2771},
								name: "DRollExpr",
							},
						},
						&litMatcher{
							pos:        position{line: 117, col: 43, offset: 2781},
							val:        ")",
							ignoreCase: false,
						},
					},
				},
			},
		},
		{
			name: "DRollExprUnaryPlus",
			pos:  position{line: 121, col: 1, offset: 2816},
			expr: &actionExpr{
				pos: position{line: 121, col: 23, offset: 2838},
				run: (*parser).callonDRollExprUnaryPlus1,
				expr: &seqExpr{
					pos: position{line: 121, col: 23, offset: 2838},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 121, col: 23, offset: 2838},
							val:        "+",
							ignoreCase: false,
						},
						&labeledExpr{
							pos:   position{line: 121, col: 27, offset: 2842},
							label: "e",
							expr: &ruleRefExpr{
								pos:  position{line: 121, col: 29, offset: 2844},
								name: "DRollExprPrimary",
							},
						},
					},
				},
			},
		},
		{
			name: "DRollExprUnaryMinus",
			pos:  position{line: 125, col: 1, offset: 2892},
			expr: &actionExpr{
				pos: position{line: 125, col: 24, offset: 2915},
				run: (*parser).callonDRollExprUnaryMinus1,
				expr: &seqExpr{
					pos: position{line: 125, col: 24, offset: 2915},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 125, col: 24, offset: 2915},
							val:        "-",
							ignoreCase: false,
						},
						&labeledExpr{
							pos:   position{line: 125, col: 28, offset: 2919},
							label: "e",
							expr: &ruleRefExpr{
								pos:  position{line: 125, col: 30, offset: 2921},
								name: "DRollExprPrimary",
							},
						},
					},
				},
			},
		},
		{
			name: "IntRandExpr",
			pos:  position{line: 129, col: 1, offset: 2989},
			expr: &ruleRefExpr{
				pos:  position{line: 129, col: 16, offset: 3004},
				name: "IntRandExprAdditive",
			},
		},
		{
			name: "IntRandExprAdditive",
			pos:  position{line: 131, col: 1, offset: 3025},
			expr: &actionExpr{
				pos: position{line: 131, col: 24, offset: 3048},
				run: (*parser).callonIntRandExprAdditive1,
				expr: &seqExpr{
					pos: position{line: 131, col: 24, offset: 3048},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 131, col: 24, offset: 3048},
							label: "first",
							expr: &ruleRefExpr{
								pos:  position{line: 131, col: 30, offset: 3054},
								name: "IntRandExprMultitive",
							},
						},
						&labeledExpr{
							pos:   position{line: 131, col: 51, offset: 3075},
							label: "rest",
							expr: &zeroOrMoreExpr{
								pos: position{line: 131, col: 56, offset: 3080},
								expr: &seqExpr{
									pos: position{line: 131, col: 57, offset: 3081},
									exprs: []interface{}{
										&choiceExpr{
											pos: position{line: 131, col: 58, offset: 3082},
											alternatives: []interface{}{
												&litMatcher{
													pos:        position{line: 131, col: 58, offset: 3082},
													val:        "+",
													ignoreCase: false,
												},
												&litMatcher{
													pos:        position{line: 131, col: 64, offset: 3088},
													val:        "-",
													ignoreCase: false,
												},
											},
										},
										&ruleRefExpr{
											pos:  position{line: 131, col: 69, offset: 3093},
											name: "IntRandExprMultitive",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "IntRandExprMultitive",
			pos:  position{line: 135, col: 1, offset: 3166},
			expr: &actionExpr{
				pos: position{line: 135, col: 25, offset: 3190},
				run: (*parser).callonIntRandExprMultitive1,
				expr: &seqExpr{
					pos: position{line: 135, col: 25, offset: 3190},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 135, col: 25, offset: 3190},
							label: "first",
							expr: &ruleRefExpr{
								pos:  position{line: 135, col: 31, offset: 3196},
								name: "IntRandExprPrimary",
							},
						},
						&labeledExpr{
							pos:   position{line: 135, col: 50, offset: 3215},
							label: "rest",
							expr: &zeroOrMoreExpr{
								pos: position{line: 135, col: 55, offset: 3220},
								expr: &choiceExpr{
									pos: position{line: 135, col: 56, offset: 3221},
									alternatives: []interface{}{
										&seqExpr{
											pos: position{line: 135, col: 56, offset: 3221},
											exprs: []interface{}{
												&litMatcher{
													pos:        position{line: 135, col: 56, offset: 3221},
													val:        "/",
													ignoreCase: false,
												},
												&ruleRefExpr{
													pos:  position{line: 135, col: 60, offset: 3225},
													name: "IntRandExprPrimary",
												},
												&charClassMatcher{
													pos:        position{line: 135, col: 79, offset: 3244},
													val:        "[ur]i",
													chars:      []rune{'u', 'r'},
													ignoreCase: true,
													inverted:   false,
												},
											},
										},
										&seqExpr{
											pos: position{line: 135, col: 88, offset: 3253},
											exprs: []interface{}{
												&choiceExpr{
													pos: position{line: 135, col: 89, offset: 3254},
													alternatives: []interface{}{
														&litMatcher{
															pos:        position{line: 135, col: 89, offset: 3254},
															val:        "*",
															ignoreCase: false,
														},
														&litMatcher{
															pos:        position{line: 135, col: 95, offset: 3260},
															val:        "/",
															ignoreCase: false,
														},
													},
												},
												&ruleRefExpr{
													pos:  position{line: 135, col: 100, offset: 3265},
													name: "IntRandExprPrimary",
												},
											},
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "IntRandExprPrimary",
			pos:  position{line: 139, col: 1, offset: 3338},
			expr: &choiceExpr{
				pos: position{line: 139, col: 23, offset: 3360},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 139, col: 23, offset: 3360},
						name: "Integer",
					},
					&ruleRefExpr{
						pos:  position{line: 139, col: 33, offset: 3370},
						name: "Rand",
					},
					&ruleRefExpr{
						pos:  position{line: 139, col: 40, offset: 3377},
						name: "IntRandExprUnaryPlus",
					},
					&ruleRefExpr{
						pos:  position{line: 139, col: 63, offset: 3400},
						name: "IntRandExprUnaryMinus",
					},
					&ruleRefExpr{
						pos:  position{line: 139, col: 87, offset: 3424},
						name: "ParenthesizedIntRandExpr",
					},
				},
			},
		},
		{
			name: "ParenthesizedIntRandExpr",
			pos:  position{line: 141, col: 1, offset: 3450},
			expr: &actionExpr{
				pos: position{line: 141, col: 29, offset: 3478},
				run: (*parser).callonParenthesizedIntRandExpr1,
				expr: &seqExpr{
					pos: position{line: 141, col: 29, offset: 3478},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 141, col: 29, offset: 3478},
							val:        "(",
							ignoreCase: false,
						},
						&labeledExpr{
							pos:   position{line: 141, col: 33, offset: 3482},
							label: "e",
							expr: &ruleRefExpr{
								pos:  position{line: 141, col: 35, offset: 3484},
								name: "IntRandExpr",
							},
						},
						&litMatcher{
							pos:        position{line: 141, col: 47, offset: 3496},
							val:        ")",
							ignoreCase: false,
						},
					},
				},
			},
		},
		{
			name: "IntRandExprUnaryPlus",
			pos:  position{line: 145, col: 1, offset: 3531},
			expr: &actionExpr{
				pos: position{line: 145, col: 25, offset: 3555},
				run: (*parser).callonIntRandExprUnaryPlus1,
				expr: &seqExpr{
					pos: position{line: 145, col: 25, offset: 3555},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 145, col: 25, offset: 3555},
							val:        "+",
							ignoreCase: false,
						},
						&labeledExpr{
							pos:   position{line: 145, col: 29, offset: 3559},
							label: "e",
							expr: &ruleRefExpr{
								pos:  position{line: 145, col: 31, offset: 3561},
								name: "IntRandExprPrimary",
							},
						},
					},
				},
			},
		},
		{
			name: "IntRandExprUnaryMinus",
			pos:  position{line: 149, col: 1, offset: 3611},
			expr: &actionExpr{
				pos: position{line: 149, col: 26, offset: 3636},
				run: (*parser).callonIntRandExprUnaryMinus1,
				expr: &seqExpr{
					pos: position{line: 149, col: 26, offset: 3636},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 149, col: 26, offset: 3636},
							val:        "-",
							ignoreCase: false,
						},
						&labeledExpr{
							pos:   position{line: 149, col: 30, offset: 3640},
							label: "e",
							expr: &ruleRefExpr{
								pos:  position{line: 149, col: 32, offset: 3642},
								name: "IntRandExprPrimary",
							},
						},
					},
				},
			},
		},
		{
			name: "DRoll",
			pos:  position{line: 153, col: 1, offset: 3712},
			expr: &actionExpr{
				pos: position{line: 153, col: 10, offset: 3721},
				run: (*parser).callonDRoll1,
				expr: &seqExpr{
					pos: position{line: 153, col: 10, offset: 3721},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 153, col: 10, offset: 3721},
							label: "num",
							expr: &ruleRefExpr{
								pos:  position{line: 153, col: 14, offset: 3725},
								name: "RollOperand",
							},
						},
						&litMatcher{
							pos:        position{line: 153, col: 26, offset: 3737},
							val:        "d",
							ignoreCase: true,
						},
						&labeledExpr{
							pos:   position{line: 153, col: 31, offset: 3742},
							label: "sides",
							expr: &ruleRefExpr{
								pos:  position{line: 153, col: 37, offset: 3748},
								name: "RollOperand",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 153, col: 49, offset: 3760},
							name: "IncRandCount",
						},
					},
				},
			},
		},
		{
			name: "RollOperand",
			pos:  position{line: 160, col: 1, offset: 3884},
			expr: &choiceExpr{
				pos: position{line: 160, col: 16, offset: 3899},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 160, col: 16, offset: 3899},
						name: "Integer",
					},
					&ruleRefExpr{
						pos:  position{line: 160, col: 26, offset: 3909},
						name: "Rand",
					},
					&ruleRefExpr{
						pos:  position{line: 160, col: 33, offset: 3916},
						name: "ParenthesizedIntRandExpr",
					},
				},
			},
		},
		{
			name: "Rand",
			pos:  position{line: 162, col: 1, offset: 3942},
			expr: &actionExpr{
				pos: position{line: 162, col: 9, offset: 3950},
				run: (*parser).callonRand1,
				expr: &seqExpr{
					pos: position{line: 162, col: 9, offset: 3950},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 162, col: 9, offset: 3950},
							val:        "[",
							ignoreCase: false,
						},
						&labeledExpr{
							pos:   position{line: 162, col: 13, offset: 3954},
							label: "min",
							expr: &ruleRefExpr{
								pos:  position{line: 162, col: 17, offset: 3958},
								name: "RandOperand",
							},
						},
						&litMatcher{
							pos:        position{line: 162, col: 29, offset: 3970},
							val:        "...",
							ignoreCase: false,
						},
						&labeledExpr{
							pos:   position{line: 162, col: 35, offset: 3976},
							label: "max",
							expr: &ruleRefExpr{
								pos:  position{line: 162, col: 39, offset: 3980},
								name: "RandOperand",
							},
						},
						&litMatcher{
							pos:        position{line: 162, col: 51, offset: 3992},
							val:        "]",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 162, col: 55, offset: 3996},
							name: "IncRandCount",
						},
					},
				},
			},
		},
		{
			name: "RandOperand",
			pos:  position{line: 169, col: 1, offset: 4121},
			expr: &choiceExpr{
				pos: position{line: 169, col: 16, offset: 4136},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 169, col: 16, offset: 4136},
						name: "Integer",
					},
					&ruleRefExpr{
						pos:  position{line: 169, col: 26, offset: 4146},
						name: "ParenthesizedIntExpr",
					},
				},
			},
		},
		{
			name: "IncRandCount",
			pos:  position{line: 171, col: 1, offset: 4168},
			expr: &stateCodeExpr{
				pos: position{line: 171, col: 17, offset: 4184},
				run: (*parser).callonIncRandCount1,
			},
		},
		{
			name: "Integer",
			pos:  position{line: 176, col: 1, offset: 4257},
			expr: &actionExpr{
				pos: position{line: 176, col: 12, offset: 4268},
				run: (*parser).callonInteger1,
				expr: &oneOrMoreExpr{
					pos: position{line: 176, col: 12, offset: 4268},
					expr: &charClassMatcher{
						pos:        position{line: 176, col: 12, offset: 4268},
						val:        "[0-9]",
						ranges:     []rune{'0', '9'},
						ignoreCase: false,
						inverted:   false,
					},
				},
			},
		},
		{
			name: "EOT",
			pos:  position{line: 185, col: 1, offset: 4438},
			expr: &notExpr{
				pos: position{line: 185, col: 8, offset: 4445},
				expr: &anyMatcher{
					line: 185, col: 9, offset: 4446,
				},
			},
		},
	},
}

func (c *current) onCommand1(n interface{}) (interface{}, error) {
	return n, nil
}

func (p *parser) callonCommand1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCommand1(stack["n"])
}

func (c *current) onCalc1(calc, expr interface{}) (interface{}, error) {
	return ast.NewCalc2(expr.(ast.Node)), nil
}

func (p *parser) callonCalc1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCalc1(stack["calc"], stack["expr"])
}

func (c *current) onDRollExprCommand3() error {
	c.state["RandCount"] = 0
	return nil
}

func (p *parser) callonDRollExprCommand3() error {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDRollExprCommand3()
}

func (c *current) onDRollExprCommand1(expr interface{}) (interface{}, error) {
	if c.state["RandCount"].(int) < 1 {
		return nil, fmt.Errorf("random element not found")
	}

	return ast.NewDRollExpr2(expr.(ast.Node)), nil
}

func (p *parser) callonDRollExprCommand1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDRollExprCommand1(stack["expr"])
}

func (c *current) onIntExprAdditive1(first, rest interface{}) (interface{}, error) {
	return leftAssociativeAdditive(first, rest)
}

func (p *parser) callonIntExprAdditive1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onIntExprAdditive1(stack["first"], stack["rest"])
}

func (c *current) onIntExprMultitive1(first, rest interface{}) (interface{}, error) {
	return leftAssociativeMultitive(first, rest)
}

func (p *parser) callonIntExprMultitive1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onIntExprMultitive1(stack["first"], stack["rest"])
}

func (c *current) onParenthesizedIntExpr1(e interface{}) (interface{}, error) {
	return e.(ast.Node), nil
}

func (p *parser) callonParenthesizedIntExpr1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onParenthesizedIntExpr1(stack["e"])
}

func (c *current) onIntExprUnaryPlus1(e interface{}) (interface{}, error) {
	return e.(ast.Node), nil
}

func (p *parser) callonIntExprUnaryPlus1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onIntExprUnaryPlus1(stack["e"])
}

func (c *current) onIntExprUnaryMinus1(e interface{}) (interface{}, error) {
	return ast.NewUnaryMinus2(e.(ast.Node)), nil
}

func (p *parser) callonIntExprUnaryMinus1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onIntExprUnaryMinus1(stack["e"])
}

func (c *current) onDRollExprAdditive1(first, rest interface{}) (interface{}, error) {
	return leftAssociativeAdditive(first, rest)
}

func (p *parser) callonDRollExprAdditive1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDRollExprAdditive1(stack["first"], stack["rest"])
}

func (c *current) onDRollExprMultitive1(first, rest interface{}) (interface{}, error) {
	return leftAssociativeMultitive(first, rest)
}

func (p *parser) callonDRollExprMultitive1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDRollExprMultitive1(stack["first"], stack["rest"])
}

func (c *current) onParenthesizedDRollExpr1(e interface{}) (interface{}, error) {
	return e.(ast.Node), nil
}

func (p *parser) callonParenthesizedDRollExpr1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onParenthesizedDRollExpr1(stack["e"])
}

func (c *current) onDRollExprUnaryPlus1(e interface{}) (interface{}, error) {
	return e.(ast.Node), nil
}

func (p *parser) callonDRollExprUnaryPlus1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDRollExprUnaryPlus1(stack["e"])
}

func (c *current) onDRollExprUnaryMinus1(e interface{}) (interface{}, error) {
	return ast.NewUnaryMinus2(e.(ast.Node)), nil
}

func (p *parser) callonDRollExprUnaryMinus1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDRollExprUnaryMinus1(stack["e"])
}

func (c *current) onIntRandExprAdditive1(first, rest interface{}) (interface{}, error) {
	return leftAssociativeAdditive(first, rest)
}

func (p *parser) callonIntRandExprAdditive1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onIntRandExprAdditive1(stack["first"], stack["rest"])
}

func (c *current) onIntRandExprMultitive1(first, rest interface{}) (interface{}, error) {
	return leftAssociativeMultitive(first, rest)
}

func (p *parser) callonIntRandExprMultitive1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onIntRandExprMultitive1(stack["first"], stack["rest"])
}

func (c *current) onParenthesizedIntRandExpr1(e interface{}) (interface{}, error) {
	return e.(ast.Node), nil
}

func (p *parser) callonParenthesizedIntRandExpr1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onParenthesizedIntRandExpr1(stack["e"])
}

func (c *current) onIntRandExprUnaryPlus1(e interface{}) (interface{}, error) {
	return e.(ast.Node), nil
}

func (p *parser) callonIntRandExprUnaryPlus1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onIntRandExprUnaryPlus1(stack["e"])
}

func (c *current) onIntRandExprUnaryMinus1(e interface{}) (interface{}, error) {
	return ast.NewUnaryMinus2(e.(ast.Node)), nil
}

func (p *parser) callonIntRandExprUnaryMinus1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onIntRandExprUnaryMinus1(stack["e"])
}

func (c *current) onDRoll1(num, sides interface{}) (interface{}, error) {
	numNode := num.(ast.Node)
	sidesNode := sides.(ast.Node)

	return ast.NewDRoll2(numNode, sidesNode), nil
}

func (p *parser) callonDRoll1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDRoll1(stack["num"], stack["sides"])
}

func (c *current) onRand1(min, max interface{}) (interface{}, error) {
	minNode := min.(ast.Node)
	maxNode := max.(ast.Node)

	return ast.NewRandomNumber2(minNode, maxNode), nil
}

func (p *parser) callonRand1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onRand1(stack["min"], stack["max"])
}

func (c *current) onIncRandCount1() error {
	c.state["RandCount"] = c.state["RandCount"].(int) + 1
	return nil
}

func (p *parser) callonIncRandCount1() error {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onIncRandCount1()
}

func (c *current) onInteger1() (interface{}, error) {
	s := string(c.text)

	// TODO: 整数が大きすぎるときなどのエラー処理が必要
	value, _ := strconv.Atoi(s)

	return ast.NewInt2(value), nil
}

func (p *parser) callonInteger1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onInteger1()
}

var (
	// errNoRule is returned when the grammar to parse has no rule.
	errNoRule = errors.New("grammar has no rule")

	// errInvalidEntrypoint is returned when the specified entrypoint rule
	// does not exit.
	errInvalidEntrypoint = errors.New("invalid entrypoint")

	// errInvalidEncoding is returned when the source is not properly
	// utf8-encoded.
	errInvalidEncoding = errors.New("invalid encoding")

	// errMaxExprCnt is used to signal that the maximum number of
	// expressions have been parsed.
	errMaxExprCnt = errors.New("max number of expresssions parsed")
)

// Option is a function that can set an option on the parser. It returns
// the previous setting as an Option.
type Option func(*parser) Option

// MaxExpressions creates an Option to stop parsing after the provided
// number of expressions have been parsed, if the value is 0 then the parser will
// parse for as many steps as needed (possibly an infinite number).
//
// The default for maxExprCnt is 0.
func MaxExpressions(maxExprCnt uint64) Option {
	return func(p *parser) Option {
		oldMaxExprCnt := p.maxExprCnt
		p.maxExprCnt = maxExprCnt
		return MaxExpressions(oldMaxExprCnt)
	}
}

// Entrypoint creates an Option to set the rule name to use as entrypoint.
// The rule name must have been specified in the -alternate-entrypoints
// if generating the parser with the -optimize-grammar flag, otherwise
// it may have been optimized out. Passing an empty string sets the
// entrypoint to the first rule in the grammar.
//
// The default is to start parsing at the first rule in the grammar.
func Entrypoint(ruleName string) Option {
	return func(p *parser) Option {
		oldEntrypoint := p.entrypoint
		p.entrypoint = ruleName
		if ruleName == "" {
			p.entrypoint = g.rules[0].name
		}
		return Entrypoint(oldEntrypoint)
	}
}

// Statistics adds a user provided Stats struct to the parser to allow
// the user to process the results after the parsing has finished.
// Also the key for the "no match" counter is set.
//
// Example usage:
//
//     input := "input"
//     stats := Stats{}
//     _, err := Parse("input-file", []byte(input), Statistics(&stats, "no match"))
//     if err != nil {
//         log.Panicln(err)
//     }
//     b, err := json.MarshalIndent(stats.ChoiceAltCnt, "", "  ")
//     if err != nil {
//         log.Panicln(err)
//     }
//     fmt.Println(string(b))
//
func Statistics(stats *Stats, choiceNoMatch string) Option {
	return func(p *parser) Option {
		oldStats := p.Stats
		p.Stats = stats
		oldChoiceNoMatch := p.choiceNoMatch
		p.choiceNoMatch = choiceNoMatch
		if p.Stats.ChoiceAltCnt == nil {
			p.Stats.ChoiceAltCnt = make(map[string]map[string]int)
		}
		return Statistics(oldStats, oldChoiceNoMatch)
	}
}

// Debug creates an Option to set the debug flag to b. When set to true,
// debugging information is printed to stdout while parsing.
//
// The default is false.
func Debug(b bool) Option {
	return func(p *parser) Option {
		old := p.debug
		p.debug = b
		return Debug(old)
	}
}

// Memoize creates an Option to set the memoize flag to b. When set to true,
// the parser will cache all results so each expression is evaluated only
// once. This guarantees linear parsing time even for pathological cases,
// at the expense of more memory and slower times for typical cases.
//
// The default is false.
func Memoize(b bool) Option {
	return func(p *parser) Option {
		old := p.memoize
		p.memoize = b
		return Memoize(old)
	}
}

// AllowInvalidUTF8 creates an Option to allow invalid UTF-8 bytes.
// Every invalid UTF-8 byte is treated as a utf8.RuneError (U+FFFD)
// by character class matchers and is matched by the any matcher.
// The returned matched value, c.text and c.offset are NOT affected.
//
// The default is false.
func AllowInvalidUTF8(b bool) Option {
	return func(p *parser) Option {
		old := p.allowInvalidUTF8
		p.allowInvalidUTF8 = b
		return AllowInvalidUTF8(old)
	}
}

// Recover creates an Option to set the recover flag to b. When set to
// true, this causes the parser to recover from panics and convert it
// to an error. Setting it to false can be useful while debugging to
// access the full stack trace.
//
// The default is true.
func Recover(b bool) Option {
	return func(p *parser) Option {
		old := p.recover
		p.recover = b
		return Recover(old)
	}
}

// GlobalStore creates an Option to set a key to a certain value in
// the globalStore.
func GlobalStore(key string, value interface{}) Option {
	return func(p *parser) Option {
		old := p.cur.globalStore[key]
		p.cur.globalStore[key] = value
		return GlobalStore(key, old)
	}
}

// InitState creates an Option to set a key to a certain value in
// the global "state" store.
func InitState(key string, value interface{}) Option {
	return func(p *parser) Option {
		old := p.cur.state[key]
		p.cur.state[key] = value
		return InitState(key, old)
	}
}

// ParseFile parses the file identified by filename.
func ParseFile(filename string, opts ...Option) (i interface{}, err error) {
	f, err := os.Open(filename)
	if err != nil {
		return nil, err
	}
	defer func() {
		if closeErr := f.Close(); closeErr != nil {
			err = closeErr
		}
	}()
	return ParseReader(filename, f, opts...)
}

// ParseReader parses the data from r using filename as information in the
// error messages.
func ParseReader(filename string, r io.Reader, opts ...Option) (interface{}, error) {
	b, err := ioutil.ReadAll(r)
	if err != nil {
		return nil, err
	}

	return Parse(filename, b, opts...)
}

// Parse parses the data from b using filename as information in the
// error messages.
func Parse(filename string, b []byte, opts ...Option) (interface{}, error) {
	return newParser(filename, b, opts...).parse(g)
}

// position records a position in the text.
type position struct {
	line, col, offset int
}

func (p position) String() string {
	return fmt.Sprintf("%d:%d [%d]", p.line, p.col, p.offset)
}

// savepoint stores all state required to go back to this point in the
// parser.
type savepoint struct {
	position
	rn rune
	w  int
}

type current struct {
	pos  position // start position of the match
	text []byte   // raw text of the match

	// state is a store for arbitrary key,value pairs that the user wants to be
	// tied to the backtracking of the parser.
	// This is always rolled back if a parsing rule fails.
	state storeDict

	// globalStore is a general store for the user to store arbitrary key-value
	// pairs that they need to manage and that they do not want tied to the
	// backtracking of the parser. This is only modified by the user and never
	// rolled back by the parser. It is always up to the user to keep this in a
	// consistent state.
	globalStore storeDict
}

type storeDict map[string]interface{}

// the AST types...

type grammar struct {
	pos   position
	rules []*rule
}

type rule struct {
	pos         position
	name        string
	displayName string
	expr        interface{}
}

type choiceExpr struct {
	pos          position
	alternatives []interface{}
}

type actionExpr struct {
	pos  position
	expr interface{}
	run  func(*parser) (interface{}, error)
}

type recoveryExpr struct {
	pos          position
	expr         interface{}
	recoverExpr  interface{}
	failureLabel []string
}

type seqExpr struct {
	pos   position
	exprs []interface{}
}

type throwExpr struct {
	pos   position
	label string
}

type labeledExpr struct {
	pos   position
	label string
	expr  interface{}
}

type expr struct {
	pos  position
	expr interface{}
}

type andExpr expr
type notExpr expr
type zeroOrOneExpr expr
type zeroOrMoreExpr expr
type oneOrMoreExpr expr

type ruleRefExpr struct {
	pos  position
	name string
}

type stateCodeExpr struct {
	pos position
	run func(*parser) error
}

type andCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type notCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type litMatcher struct {
	pos        position
	val        string
	ignoreCase bool
}

type charClassMatcher struct {
	pos             position
	val             string
	basicLatinChars [128]bool
	chars           []rune
	ranges          []rune
	classes         []*unicode.RangeTable
	ignoreCase      bool
	inverted        bool
}

type anyMatcher position

// errList cumulates the errors found by the parser.
type errList []error

func (e *errList) add(err error) {
	*e = append(*e, err)
}

func (e errList) err() error {
	if len(e) == 0 {
		return nil
	}
	e.dedupe()
	return e
}

func (e *errList) dedupe() {
	var cleaned []error
	set := make(map[string]bool)
	for _, err := range *e {
		if msg := err.Error(); !set[msg] {
			set[msg] = true
			cleaned = append(cleaned, err)
		}
	}
	*e = cleaned
}

func (e errList) Error() string {
	switch len(e) {
	case 0:
		return ""
	case 1:
		return e[0].Error()
	default:
		var buf bytes.Buffer

		for i, err := range e {
			if i > 0 {
				buf.WriteRune('\n')
			}
			buf.WriteString(err.Error())
		}
		return buf.String()
	}
}

// parserError wraps an error with a prefix indicating the rule in which
// the error occurred. The original error is stored in the Inner field.
type parserError struct {
	Inner    error
	pos      position
	prefix   string
	expected []string
}

// Error returns the error message.
func (p *parserError) Error() string {
	return p.prefix + ": " + p.Inner.Error()
}

// newParser creates a parser with the specified input source and options.
func newParser(filename string, b []byte, opts ...Option) *parser {
	stats := Stats{
		ChoiceAltCnt: make(map[string]map[string]int),
	}

	p := &parser{
		filename: filename,
		errs:     new(errList),
		data:     b,
		pt:       savepoint{position: position{line: 1}},
		recover:  true,
		cur: current{
			state:       make(storeDict),
			globalStore: make(storeDict),
		},
		maxFailPos:      position{col: 1, line: 1},
		maxFailExpected: make([]string, 0, 20),
		Stats:           &stats,
		// start rule is rule [0] unless an alternate entrypoint is specified
		entrypoint: g.rules[0].name,
	}
	p.setOptions(opts)

	if p.maxExprCnt == 0 {
		p.maxExprCnt = math.MaxUint64
	}

	return p
}

// setOptions applies the options to the parser.
func (p *parser) setOptions(opts []Option) {
	for _, opt := range opts {
		opt(p)
	}
}

type resultTuple struct {
	v   interface{}
	b   bool
	end savepoint
}

const choiceNoMatch = -1

// Stats stores some statistics, gathered during parsing
type Stats struct {
	// ExprCnt counts the number of expressions processed during parsing
	// This value is compared to the maximum number of expressions allowed
	// (set by the MaxExpressions option).
	ExprCnt uint64

	// ChoiceAltCnt is used to count for each ordered choice expression,
	// which alternative is used how may times.
	// These numbers allow to optimize the order of the ordered choice expression
	// to increase the performance of the parser
	//
	// The outer key of ChoiceAltCnt is composed of the name of the rule as well
	// as the line and the column of the ordered choice.
	// The inner key of ChoiceAltCnt is the number (one-based) of the matching alternative.
	// For each alternative the number of matches are counted. If an ordered choice does not
	// match, a special counter is incremented. The name of this counter is set with
	// the parser option Statistics.
	// For an alternative to be included in ChoiceAltCnt, it has to match at least once.
	ChoiceAltCnt map[string]map[string]int
}

type parser struct {
	filename string
	pt       savepoint
	cur      current

	data []byte
	errs *errList

	depth   int
	recover bool
	debug   bool

	memoize bool
	// memoization table for the packrat algorithm:
	// map[offset in source] map[expression or rule] {value, match}
	memo map[int]map[interface{}]resultTuple

	// rules table, maps the rule identifier to the rule node
	rules map[string]*rule
	// variables stack, map of label to value
	vstack []map[string]interface{}
	// rule stack, allows identification of the current rule in errors
	rstack []*rule

	// parse fail
	maxFailPos            position
	maxFailExpected       []string
	maxFailInvertExpected bool

	// max number of expressions to be parsed
	maxExprCnt uint64
	// entrypoint for the parser
	entrypoint string

	allowInvalidUTF8 bool

	*Stats

	choiceNoMatch string
	// recovery expression stack, keeps track of the currently available recovery expression, these are traversed in reverse
	recoveryStack []map[string]interface{}
}

// push a variable set on the vstack.
func (p *parser) pushV() {
	if cap(p.vstack) == len(p.vstack) {
		// create new empty slot in the stack
		p.vstack = append(p.vstack, nil)
	} else {
		// slice to 1 more
		p.vstack = p.vstack[:len(p.vstack)+1]
	}

	// get the last args set
	m := p.vstack[len(p.vstack)-1]
	if m != nil && len(m) == 0 {
		// empty map, all good
		return
	}

	m = make(map[string]interface{})
	p.vstack[len(p.vstack)-1] = m
}

// pop a variable set from the vstack.
func (p *parser) popV() {
	// if the map is not empty, clear it
	m := p.vstack[len(p.vstack)-1]
	if len(m) > 0 {
		// GC that map
		p.vstack[len(p.vstack)-1] = nil
	}
	p.vstack = p.vstack[:len(p.vstack)-1]
}

// push a recovery expression with its labels to the recoveryStack
func (p *parser) pushRecovery(labels []string, expr interface{}) {
	if cap(p.recoveryStack) == len(p.recoveryStack) {
		// create new empty slot in the stack
		p.recoveryStack = append(p.recoveryStack, nil)
	} else {
		// slice to 1 more
		p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)+1]
	}

	m := make(map[string]interface{}, len(labels))
	for _, fl := range labels {
		m[fl] = expr
	}
	p.recoveryStack[len(p.recoveryStack)-1] = m
}

// pop a recovery expression from the recoveryStack
func (p *parser) popRecovery() {
	// GC that map
	p.recoveryStack[len(p.recoveryStack)-1] = nil

	p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)-1]
}

func (p *parser) print(prefix, s string) string {
	if !p.debug {
		return s
	}

	fmt.Printf("%s %d:%d:%d: %s [%#U]\n",
		prefix, p.pt.line, p.pt.col, p.pt.offset, s, p.pt.rn)
	return s
}

func (p *parser) in(s string) string {
	p.depth++
	return p.print(strings.Repeat(" ", p.depth)+">", s)
}

func (p *parser) out(s string) string {
	p.depth--
	return p.print(strings.Repeat(" ", p.depth)+"<", s)
}

func (p *parser) addErr(err error) {
	p.addErrAt(err, p.pt.position, []string{})
}

func (p *parser) addErrAt(err error, pos position, expected []string) {
	var buf bytes.Buffer
	if p.filename != "" {
		buf.WriteString(p.filename)
	}
	if buf.Len() > 0 {
		buf.WriteString(":")
	}
	buf.WriteString(fmt.Sprintf("%d:%d (%d)", pos.line, pos.col, pos.offset))
	if len(p.rstack) > 0 {
		if buf.Len() > 0 {
			buf.WriteString(": ")
		}
		rule := p.rstack[len(p.rstack)-1]
		if rule.displayName != "" {
			buf.WriteString("rule " + rule.displayName)
		} else {
			buf.WriteString("rule " + rule.name)
		}
	}
	pe := &parserError{Inner: err, pos: pos, prefix: buf.String(), expected: expected}
	p.errs.add(pe)
}

func (p *parser) failAt(fail bool, pos position, want string) {
	// process fail if parsing fails and not inverted or parsing succeeds and invert is set
	if fail == p.maxFailInvertExpected {
		if pos.offset < p.maxFailPos.offset {
			return
		}

		if pos.offset > p.maxFailPos.offset {
			p.maxFailPos = pos
			p.maxFailExpected = p.maxFailExpected[:0]
		}

		if p.maxFailInvertExpected {
			want = "!" + want
		}
		p.maxFailExpected = append(p.maxFailExpected, want)
	}
}

// read advances the parser to the next rune.
func (p *parser) read() {
	p.pt.offset += p.pt.w
	rn, n := utf8.DecodeRune(p.data[p.pt.offset:])
	p.pt.rn = rn
	p.pt.w = n
	p.pt.col++
	if rn == '\n' {
		p.pt.line++
		p.pt.col = 0
	}

	if rn == utf8.RuneError && n == 1 { // see utf8.DecodeRune
		if !p.allowInvalidUTF8 {
			p.addErr(errInvalidEncoding)
		}
	}
}

// restore parser position to the savepoint pt.
func (p *parser) restore(pt savepoint) {
	if p.debug {
		defer p.out(p.in("restore"))
	}
	if pt.offset == p.pt.offset {
		return
	}
	p.pt = pt
}

// Cloner is implemented by any value that has a Clone method, which returns a
// copy of the value. This is mainly used for types which are not passed by
// value (e.g map, slice, chan) or structs that contain such types.
//
// This is used in conjunction with the global state feature to create proper
// copies of the state to allow the parser to properly restore the state in
// the case of backtracking.
type Cloner interface {
	Clone() interface{}
}

// clone and return parser current state.
func (p *parser) cloneState() storeDict {
	if p.debug {
		defer p.out(p.in("cloneState"))
	}

	state := make(storeDict, len(p.cur.state))
	for k, v := range p.cur.state {
		if c, ok := v.(Cloner); ok {
			state[k] = c.Clone()
		} else {
			state[k] = v
		}
	}
	return state
}

// restore parser current state to the state storeDict.
// every restoreState should applied only one time for every cloned state
func (p *parser) restoreState(state storeDict) {
	if p.debug {
		defer p.out(p.in("restoreState"))
	}
	p.cur.state = state
}

// get the slice of bytes from the savepoint start to the current position.
func (p *parser) sliceFrom(start savepoint) []byte {
	return p.data[start.position.offset:p.pt.position.offset]
}

func (p *parser) getMemoized(node interface{}) (resultTuple, bool) {
	if len(p.memo) == 0 {
		return resultTuple{}, false
	}
	m := p.memo[p.pt.offset]
	if len(m) == 0 {
		return resultTuple{}, false
	}
	res, ok := m[node]
	return res, ok
}

func (p *parser) setMemoized(pt savepoint, node interface{}, tuple resultTuple) {
	if p.memo == nil {
		p.memo = make(map[int]map[interface{}]resultTuple)
	}
	m := p.memo[pt.offset]
	if m == nil {
		m = make(map[interface{}]resultTuple)
		p.memo[pt.offset] = m
	}
	m[node] = tuple
}

func (p *parser) buildRulesTable(g *grammar) {
	p.rules = make(map[string]*rule, len(g.rules))
	for _, r := range g.rules {
		p.rules[r.name] = r
	}
}

func (p *parser) parse(g *grammar) (val interface{}, err error) {
	if len(g.rules) == 0 {
		p.addErr(errNoRule)
		return nil, p.errs.err()
	}

	// TODO : not super critical but this could be generated
	p.buildRulesTable(g)

	if p.recover {
		// panic can be used in action code to stop parsing immediately
		// and return the panic as an error.
		defer func() {
			if e := recover(); e != nil {
				if p.debug {
					defer p.out(p.in("panic handler"))
				}
				val = nil
				switch e := e.(type) {
				case error:
					p.addErr(e)
				default:
					p.addErr(fmt.Errorf("%v", e))
				}
				err = p.errs.err()
			}
		}()
	}

	startRule, ok := p.rules[p.entrypoint]
	if !ok {
		p.addErr(errInvalidEntrypoint)
		return nil, p.errs.err()
	}

	p.read() // advance to first rune
	val, ok = p.parseRule(startRule)
	if !ok {
		if len(*p.errs) == 0 {
			// If parsing fails, but no errors have been recorded, the expected values
			// for the farthest parser position are returned as error.
			maxFailExpectedMap := make(map[string]struct{}, len(p.maxFailExpected))
			for _, v := range p.maxFailExpected {
				maxFailExpectedMap[v] = struct{}{}
			}
			expected := make([]string, 0, len(maxFailExpectedMap))
			eof := false
			if _, ok := maxFailExpectedMap["!."]; ok {
				delete(maxFailExpectedMap, "!.")
				eof = true
			}
			for k := range maxFailExpectedMap {
				expected = append(expected, k)
			}
			sort.Strings(expected)
			if eof {
				expected = append(expected, "EOF")
			}
			p.addErrAt(errors.New("no match found, expected: "+listJoin(expected, ", ", "or")), p.maxFailPos, expected)
		}

		return nil, p.errs.err()
	}
	return val, p.errs.err()
}

func listJoin(list []string, sep string, lastSep string) string {
	switch len(list) {
	case 0:
		return ""
	case 1:
		return list[0]
	default:
		return fmt.Sprintf("%s %s %s", strings.Join(list[:len(list)-1], sep), lastSep, list[len(list)-1])
	}
}

func (p *parser) parseRule(rule *rule) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRule " + rule.name))
	}

	if p.memoize {
		res, ok := p.getMemoized(rule)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
	}

	start := p.pt
	p.rstack = append(p.rstack, rule)
	p.pushV()
	val, ok := p.parseExpr(rule.expr)
	p.popV()
	p.rstack = p.rstack[:len(p.rstack)-1]
	if ok && p.debug {
		p.print(strings.Repeat(" ", p.depth)+"MATCH", string(p.sliceFrom(start)))
	}

	if p.memoize {
		p.setMemoized(start, rule, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseExpr(expr interface{}) (interface{}, bool) {
	var pt savepoint

	if p.memoize {
		res, ok := p.getMemoized(expr)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
		pt = p.pt
	}

	p.ExprCnt++
	if p.ExprCnt > p.maxExprCnt {
		panic(errMaxExprCnt)
	}

	var val interface{}
	var ok bool
	switch expr := expr.(type) {
	case *actionExpr:
		val, ok = p.parseActionExpr(expr)
	case *andCodeExpr:
		val, ok = p.parseAndCodeExpr(expr)
	case *andExpr:
		val, ok = p.parseAndExpr(expr)
	case *anyMatcher:
		val, ok = p.parseAnyMatcher(expr)
	case *charClassMatcher:
		val, ok = p.parseCharClassMatcher(expr)
	case *choiceExpr:
		val, ok = p.parseChoiceExpr(expr)
	case *labeledExpr:
		val, ok = p.parseLabeledExpr(expr)
	case *litMatcher:
		val, ok = p.parseLitMatcher(expr)
	case *notCodeExpr:
		val, ok = p.parseNotCodeExpr(expr)
	case *notExpr:
		val, ok = p.parseNotExpr(expr)
	case *oneOrMoreExpr:
		val, ok = p.parseOneOrMoreExpr(expr)
	case *recoveryExpr:
		val, ok = p.parseRecoveryExpr(expr)
	case *ruleRefExpr:
		val, ok = p.parseRuleRefExpr(expr)
	case *seqExpr:
		val, ok = p.parseSeqExpr(expr)
	case *stateCodeExpr:
		val, ok = p.parseStateCodeExpr(expr)
	case *throwExpr:
		val, ok = p.parseThrowExpr(expr)
	case *zeroOrMoreExpr:
		val, ok = p.parseZeroOrMoreExpr(expr)
	case *zeroOrOneExpr:
		val, ok = p.parseZeroOrOneExpr(expr)
	default:
		panic(fmt.Sprintf("unknown expression type %T", expr))
	}
	if p.memoize {
		p.setMemoized(pt, expr, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseActionExpr(act *actionExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseActionExpr"))
	}

	start := p.pt
	val, ok := p.parseExpr(act.expr)
	if ok {
		p.cur.pos = start.position
		p.cur.text = p.sliceFrom(start)
		state := p.cloneState()
		actVal, err := act.run(p)
		if err != nil {
			p.addErrAt(err, start.position, []string{})
		}
		p.restoreState(state)

		val = actVal
	}
	if ok && p.debug {
		p.print(strings.Repeat(" ", p.depth)+"MATCH", string(p.sliceFrom(start)))
	}
	return val, ok
}

func (p *parser) parseAndCodeExpr(and *andCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAndCodeExpr"))
	}

	state := p.cloneState()

	ok, err := and.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, ok
}

func (p *parser) parseAndExpr(and *andExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAndExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	_, ok := p.parseExpr(and.expr)
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, ok
}

func (p *parser) parseAnyMatcher(any *anyMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAnyMatcher"))
	}

	if p.pt.rn == utf8.RuneError && p.pt.w == 0 {
		// EOF - see utf8.DecodeRune
		p.failAt(false, p.pt.position, ".")
		return nil, false
	}
	start := p.pt
	p.read()
	p.failAt(true, start.position, ".")
	return p.sliceFrom(start), true
}

func (p *parser) parseCharClassMatcher(chr *charClassMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseCharClassMatcher"))
	}

	cur := p.pt.rn
	start := p.pt

	// can't match EOF
	if cur == utf8.RuneError && p.pt.w == 0 { // see utf8.DecodeRune
		p.failAt(false, start.position, chr.val)
		return nil, false
	}

	if chr.ignoreCase {
		cur = unicode.ToLower(cur)
	}

	// try to match in the list of available chars
	for _, rn := range chr.chars {
		if rn == cur {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of ranges
	for i := 0; i < len(chr.ranges); i += 2 {
		if cur >= chr.ranges[i] && cur <= chr.ranges[i+1] {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of Unicode classes
	for _, cl := range chr.classes {
		if unicode.Is(cl, cur) {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	if chr.inverted {
		p.read()
		p.failAt(true, start.position, chr.val)
		return p.sliceFrom(start), true
	}
	p.failAt(false, start.position, chr.val)
	return nil, false
}

func (p *parser) incChoiceAltCnt(ch *choiceExpr, altI int) {
	choiceIdent := fmt.Sprintf("%s %d:%d", p.rstack[len(p.rstack)-1].name, ch.pos.line, ch.pos.col)
	m := p.ChoiceAltCnt[choiceIdent]
	if m == nil {
		m = make(map[string]int)
		p.ChoiceAltCnt[choiceIdent] = m
	}
	// We increment altI by 1, so the keys do not start at 0
	alt := strconv.Itoa(altI + 1)
	if altI == choiceNoMatch {
		alt = p.choiceNoMatch
	}
	m[alt]++
}

func (p *parser) parseChoiceExpr(ch *choiceExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseChoiceExpr"))
	}

	for altI, alt := range ch.alternatives {
		// dummy assignment to prevent compile error if optimized
		_ = altI

		state := p.cloneState()

		p.pushV()
		val, ok := p.parseExpr(alt)
		p.popV()
		if ok {
			p.incChoiceAltCnt(ch, altI)
			return val, ok
		}
		p.restoreState(state)
	}
	p.incChoiceAltCnt(ch, choiceNoMatch)
	return nil, false
}

func (p *parser) parseLabeledExpr(lab *labeledExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseLabeledExpr"))
	}

	p.pushV()
	val, ok := p.parseExpr(lab.expr)
	p.popV()
	if ok && lab.label != "" {
		m := p.vstack[len(p.vstack)-1]
		m[lab.label] = val
	}
	return val, ok
}

func (p *parser) parseLitMatcher(lit *litMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseLitMatcher"))
	}

	ignoreCase := ""
	if lit.ignoreCase {
		ignoreCase = "i"
	}
	val := fmt.Sprintf("%q%s", lit.val, ignoreCase)
	start := p.pt
	for _, want := range lit.val {
		cur := p.pt.rn
		if lit.ignoreCase {
			cur = unicode.ToLower(cur)
		}
		if cur != want {
			p.failAt(false, start.position, val)
			p.restore(start)
			return nil, false
		}
		p.read()
	}
	p.failAt(true, start.position, val)
	return p.sliceFrom(start), true
}

func (p *parser) parseNotCodeExpr(not *notCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseNotCodeExpr"))
	}

	state := p.cloneState()

	ok, err := not.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, !ok
}

func (p *parser) parseNotExpr(not *notExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseNotExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	_, ok := p.parseExpr(not.expr)
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, !ok
}

func (p *parser) parseOneOrMoreExpr(expr *oneOrMoreExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseOneOrMoreExpr"))
	}

	var vals []interface{}

	for {
		p.pushV()
		val, ok := p.parseExpr(expr.expr)
		p.popV()
		if !ok {
			if len(vals) == 0 {
				// did not match once, no match
				return nil, false
			}
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseRecoveryExpr(recover *recoveryExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRecoveryExpr (" + strings.Join(recover.failureLabel, ",") + ")"))
	}

	p.pushRecovery(recover.failureLabel, recover.recoverExpr)
	val, ok := p.parseExpr(recover.expr)
	p.popRecovery()

	return val, ok
}

func (p *parser) parseRuleRefExpr(ref *ruleRefExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRuleRefExpr " + ref.name))
	}

	if ref.name == "" {
		panic(fmt.Sprintf("%s: invalid rule: missing name", ref.pos))
	}

	rule := p.rules[ref.name]
	if rule == nil {
		p.addErr(fmt.Errorf("undefined rule: %s", ref.name))
		return nil, false
	}
	return p.parseRule(rule)
}

func (p *parser) parseSeqExpr(seq *seqExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseSeqExpr"))
	}

	vals := make([]interface{}, 0, len(seq.exprs))

	pt := p.pt
	state := p.cloneState()
	for _, expr := range seq.exprs {
		val, ok := p.parseExpr(expr)
		if !ok {
			p.restoreState(state)
			p.restore(pt)
			return nil, false
		}
		vals = append(vals, val)
	}
	return vals, true
}

func (p *parser) parseStateCodeExpr(state *stateCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseStateCodeExpr"))
	}

	err := state.run(p)
	if err != nil {
		p.addErr(err)
	}
	return nil, true
}

func (p *parser) parseThrowExpr(expr *throwExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseThrowExpr"))
	}

	for i := len(p.recoveryStack) - 1; i >= 0; i-- {
		if recoverExpr, ok := p.recoveryStack[i][expr.label]; ok {
			if val, ok := p.parseExpr(recoverExpr); ok {
				return val, ok
			}
		}
	}

	return nil, false
}

func (p *parser) parseZeroOrMoreExpr(expr *zeroOrMoreExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrMoreExpr"))
	}

	var vals []interface{}

	for {
		p.pushV()
		val, ok := p.parseExpr(expr.expr)
		p.popV()
		if !ok {
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseZeroOrOneExpr(expr *zeroOrOneExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrOneExpr"))
	}

	p.pushV()
	val, _ := p.parseExpr(expr.expr)
	p.popV()
	// whether it matched or not, consider it a match
	return val, true
}
