.PHONY: all clean

all:
	$(MAKE) -C GoBCDiceAPI
	$(MAKE) -C GoBCDiceCUI
	$(MAKE) -C GoBCDiceGUI
	$(MAKE) -C GoBCDiceREPL

clean:
	$(MAKE) -C GoBCDiceAPI clean
	$(MAKE) -C GoBCDiceCUI clean
	$(MAKE) -C GoBCDiceGUI clean
	$(MAKE) -C GoBCDiceREPL clean
