name: Go

on: [push, pull_request]

jobs:

  test:
    name: Test
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        go: ['1.26.0']
      fail-fast: false
    env:
      OS: ${{ matrix.os }}
      GO: ${{ matrix.go }}
    steps:
      - if: startsWith(matrix.os, 'macos')
        run: brew update

      - uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version: ${{ matrix.go }}

      - name: Get Build Tools
        run: |
          go install github.com/ory/go-acc@latest

      - name: Add $GOPATH/bin to $PATH
        run: |
          echo "$(go env GOPATH)/bin" >> "$GITHUB_PATH"

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: before get
        run: go get ./pkg/...

      - name: 'Tags: default'
        run: go-acc ./pkg/... -- -race -v

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@0561704f0f02c16a585d4c7555e57fa2e44cf909 # v5.5.2
        with:
          env_vars: OS,GO
          file: coverage.txt

  test-windows:
    name: Test for Windows
    runs-on: windows-latest

    strategy:
      matrix:
        go: ['1.26.0']
      fail-fast: false
    env:
      OS: windows-latest
      GO: ${{ matrix.go }}
    steps:
      - uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version: ${{ matrix.go }}

      - name: Get Build Tools
        run: |
          go install github.com/ory/go-acc@latest

      - name: Add $GOPATH/bin to $PATH
        run: |
          $gopath = go env GOPATH
          Add-Content -Path $env:GITHUB_PATH -Value "$gopath\bin"

      - name: git autocrlf off
        run: |
          git config --global core.autocrlf false

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: before get
        run: go get ./pkg/...

      - name: 'Tags: default'
        run: go-acc ./pkg/... -- -race -v

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@0561704f0f02c16a585d4c7555e57fa2e44cf909 # v5.5.2
        with:
          env_vars: OS,GO
          file: coverage.txt

  build:
    name: Build
    runs-on: ${{ matrix.os }}
    needs: test

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        go: ['1.26.0']
      fail-fast: false
    env:
      OS: ${{ matrix.os }}
      GO: ${{ matrix.go }}
    steps:
      - uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version: ${{ matrix.go }}
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - if: startsWith(matrix.os, 'macos')
        run: |
          ./scripts/install_prerequisites_osx.sh

      - if: startsWith(matrix.os, 'ubuntu')
        run: |
          ./scripts/install_prerequisites_linux.sh

      - run: make

  build-windows:
    name: Build for Windows
    runs-on: windows-latest
    needs: test-windows

    strategy:
      matrix:
        go: ['1.26.0']
      fail-fast: false
    env:
      OS: windows-latest
      GO: ${{ matrix.go }}
    steps:
      - uses: msys2/setup-msys2@4f806de0a5a7294ffabaff804b38a9b435a73bda # v2.30.0
        with:
          update: true
          install: mingw-w64-x86_64-toolchain mingw-w64-x86_64-gtk3
          msystem: MINGW64
          path-type: inherit

      - uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version: ${{ matrix.go }}

      - name: git autocrlf off
        run: |
          git config --global core.autocrlf false

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - run: make
        shell: msys2 {0}

# based on: github.com/koron-go/_skeleton/.github/workflows/go.yml
